### ISSUE TITLE
Following my own sharing link prompts for identity selection

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1716] opened 2016-03-28 04:33 UTC
To reproduce:

1. Create a sharing link for a grain you own.
2. Visit it.

Expected result: It opens as if visiting the grain URL directly.
Actual result: I am prompted to choose an identity or go incognito.

Related problem: If I follow a sharing link, choose an identity, then later follow the same sharing link again, I am prompted for an identity again. Seems like it should automatically choose the same identity I used previously.

**Comment by dwrensha** [comment] 2016-03-28 13:23
> If I follow a sharing link, choose an identity, then later follow the same sharing link again, I am prompted for an identity again. Seems like it should automatically choose the same identity I used previously.

If you're talking about a sharing link for a grain that you own, this should be fixed by #1718. If you're talking about other sharing links, this ought to have been fixed by #1702, and I have been unable to reproduce the problem since then.

**Comment by kentonv** [comment] 2016-03-28 20:28
@dwrensha: When I observed this I was using Oasis prior to last night's update, so that explains why #1702 wasn't doing its job.

**Closed** 2016-03-28 20:28 UTC
