### ISSUE TITLE
Server unable to create WebSocket

### ISSUE THREAD

**Issue by kodb-avv** [sandstorm-io/sandstorm#2812] opened 2017-01-03 02:29 UTC
This error appears when I access the Admin panel.  I have neither nginx nor apache2 installed or configured.  Neither directory can be found under /etc.
Sandstorm is installed via the https script on a clean ubuntu 14.04 vps on my own cluster.
Please advise if you need log contents or other inputs
Thanks
Bob

**Comment by kentonv** [comment] 2017-01-03 03:07
The problem could be on the browser side. What browser are you using, and what version? Is your browser going through an HTTP proxy (some proxies don't support WebSocket)? What kind of network is it on (some networks, especially badly-configured corporate networks, block WebSocket)?

**Comment by kodb-avv** [comment] 2017-01-03 03:10
it occurs in both Safari from my MacBook and Chrome latest on Win10 and Ubuntu 14.04.  No proxies on the lan.  My network is smallish office lan for medical office; has Cisco ASA on internet side and uses 2012R2 HyperV cluster to run all the vms/servers including the 14.04 instance hosting sandstorm
Bob

**Comment by kodb-avv** [comment] 2017-01-03 03:12
I will check on the versions in the am when I return to the office.
Thanks for the rapid feedback!
B

**Comment by kodb-avv** [comment] 2017-01-03 13:29
Good morning.  The error is gone this am (was up last pm) on both the Win10 machine and the ubuntu machine browsers (Chrome Version 55.0.2883.87 m on Windows,  55.0.2883.75 ubuntu) but remains present with same behavior in Safari (10.0.2 on OSX 10.12.2).  Interestingly, when accessing the Wekan grains via Samsung Galaxy S7 Edge, chrome there fails to allow me to click on the cards directly but I do not see the websocket error.  Should I open separate ticket for that issue?
Thanks again
B

**Comment by kentonv** [comment] 2017-01-04 01:00
> remains present with same behavior in Safari

Yeah, Apple broke Safari's WebSocket implementation in the latest OSX update. See #2578. We haven't managed to work around it yet. :(

These days most things should work OK without WebSocket. Earlier in Sandstorm's history we had problems were some apps would totally break without WebSocket, hence the warning message.

> Interestingly, when accessing the Wekan grains via Samsung Galaxy S7 Edge, chrome there fails to allow me to click on the cards directly but I do not see the websocket error. Should I open separate ticket for that issue?

Yes, probably.

**Comment by kentonv** [comment] 2017-01-04 01:01
(Closing as a duplicate of #2578.)

**Closed by kentonv** 2017-01-04 01:01 UTC
