### ISSUE TITLE
Sandstorm dialogs should not assume Alpha server

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#241] opened 2015-02-04 21:42 UTC
Sandstorm assumes the installation is meant for the Sandstorm.io alpha or demo server. Dialogs contain text such as:
"You've been invited to join the Sandstorm alpha!"
"Want an invite? Get on the mailing list."

While these could simply be made more general, it may be warranted to start extracting language to separate files, where they can be easily localized or customized.

**Comment by kentonv** [comment] 2015-02-04 21:55
Dupe of #213? Though we should add a note about the "you've been invited" text.

**Comment by ocdtrekkie** [comment] 2015-02-04 21:59
I am blaming @paulproteus since he told me to file it. They are basically the same issue, though I noticed it because of a different line, the "You've been invited" bit.

**Closed** 2015-02-04 22:21 UTC

**Comment by paulproteus** [comment] 2015-02-04 23:46
I'm indeed to blame : P Sorry about the misdirection!
