### ISSUE TITLE
Plugins/modules

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#507] opened 2015-06-17 07:56 UTC
Not sure if this is maybe explained somewhere and I missed, but how do one pack apps which have plugins/modules? For example, MediaWiki and Wordpress offer many plugins. Wordpress has a web interface to install them. Is that allowed? What is the best practice to offer such plugins? And how to pack them? It is hard to provide all possible combinations of apps for various plugins.

**Comment by ocdtrekkie** [comment] 2015-06-17 08:02
Hi! I am not a Sandstorm.io developer, but I'll regurgitate what I know. :)

Currently speaking, there is no good way to do this. Apps like Etherpad, IPython, and Wordpress are packaged for Sandstorm with any plugins the package maintainer thinks are fitting. In order to add or remove plugins, you would need to re-package the app yourself.

If WordPress has a web interface to install plugins, this is probably _possible_ to work with, however it should be noted the Sandstorm apps as a whole cannot be changed unless the relevant files live in the /var folder, which is the only part of a Sandstorm app which can be edited or used for data storage.

However, the Sandstorm team does want to implement some sort of plugin functionality that works well with these types of apps.

**Comment by zarvox** [comment] 2015-06-17 08:46
Hi @mitar!  Thanks for dropping us a line! :)

Yeah, to confirm what @ocdtrekkie said: the story today is `.spk`s include whatever packagers deem appropriate. There's no first-class explicit support for adding plugins to packages yet, but if an app supports uploading plugins, you could store the plugins under `/var` and that would likely work.  Of course, then the plugins would count against the user's disk quota, which is not ideal, but perhaps we can come up with a better solution for that in the future.  I recall discussing some half-baked ideas with @paulproteus about something like "addon `.spk`s" that might be able to add/replace files from existing apps to allow this sort of thing -- Asheesh, is there anything you'd like to add here?

It's also worth noting that plugins may have additional system library requirements, or expect to be able to access things that are not directly available in the sandbox.  For instance, by default Sandstorm apps run isolated from the network, and cannot make outgoing connections, and the only writable directory is `/var`.  If a plugin expects to be able to do something the sandbox disallows, then the plugin may or may not work.

@mitar I'd love to hear if you had a particular application or usecase in mind!  I'm definitely supportive of making plugins functional for users, and specific examples are highly motivating for making sure a design works well in practice. :)

(offtopic: I recognize you from the bid-lab-students mailinglist!  I sat in BiD and worked with Björn Hartmann and Dave Wagner on usable security stuff from 2010-2012!)

**Comment by mitar** [comment] 2015-06-17 09:18
Hm, after reading more I do not think Sandstorm meets my needs, so my usecases are probably not really useful here. So it will be probably tangential to the topic of this ticket.

It seems Sandstorm is targeting individuals. I am searching for something similar to Sandstorm, but for communities. I am researching and developing technical solutions to facilitate cooperation in communities. And there are various tools available which communities use, like Etherpad, MediaWiki, [Loomio](http://loomio.org/). But communities often do not have knowledge to install combination of those tools they need. I thought that Sandstorm could be a solution. Something they could install base for, and then just click apps they like. For example, this software suite is similar: https://intertwinkles.org/ But, the modules it offers are hard-coded. You cannot add new ones.

So, ideally, there would be some glue which would be sticking those modules together, and especially some single-sign-on authentication mechanism + some roles/groups support which all the modules would share. I find lack of all this surprising, but also something why communities then use solutions like Facebook which often do not provide tools which would facilitate dynamics in those communities (like horizontal structures, information sharing through the whole community, etc.).

Example of such communities I am looking at are intentional living communities like [Berkeley Student Cooperative](http://bsc.coop/), with 1300 members across 20 houses for who there should really be some solutions to help communicate across the whole community. There are many things such a community needs, mailing lists, ownCloud, Wordpress, workshift management, decision making/support software, etc.

Another communities I am looking at are [wireless community networks](https://en.wikipedia.org/wiki/Wireless_community_network) across the world. We developed software which allows also non-technical people to deploy mesh networks in their communities, [nodewatcher](http://nodes.wlan-si.net/). But while deployment of a new wireless node is easy and is facilitated by a web interface, deployment of a new instance of nodewatcher is pretty involved (it often has things like Internet gateways, VPN servers, etc.). If we would like that communities across the world can deploy those server installations easily, there should be again some turn-key solution. Here comes the issue of modularity. Each community is different and has different needs. Some make their networks completely open, some require authentication, some are free, others are freemium. Some use different routing protocols. With this in mind we developed nodewatcher to be modular, so that each community can deploy their own variation for their own network. But of course this makes it really hard to make it easy to install. For example, our current approach with Docker images has the same issue with modules (which are implemented as Django apps). So I was looking at Sandstorm if it solves this problem in some way. I knew that it has much smaller concept of apps than Docker. But it seems composability of those apps is not yet where I would need it. Also, it targets individual users and not communities.

Ideally, users would install a base system. And then by clicking in some admin panel they would add or remove modules they want.

(offtopic: Come to 10th BiD anniversary. I think that invitations will go out soon.)

**Comment by kentonv** [comment] 2015-06-18 18:28
@mitar Your use case of communities definitely sounds like something we intend to support.

We also definitely want to support a notion of "add-on" packages, which extend the contents of some other package with additional files. We haven't had time to implement this yet but it's on the list.

I'm not sure I completely understand, though, how communities and modularity relate. Don't individuals need modularity and customizability just as much as communities do? Aside from that and group management, are there other missing features in Sandstorm needed to support communities?

**Comment by mitar** [comment] 2015-06-18 20:23
> Your use case of communities definitely sounds like something we intend to support.

But currently your apps target single users, no? I cannot have an app which expects and works with multiple users, like [Sympa](http://www.sympa.org/) or any other forum app?

> I'm not sure I completely understand, though, how communities and modularity relate. Don't individuals need modularity and customizability just as much as communities do? Aside from that and group management, are there other missing features in Sandstorm needed to support communities?

Oh, sorry, if this was not clear. No, there is not direct relation, but it is something which comes out of the experience. No community is alike. So providing the exactly the same app with exactly the same features and workflows to all communities often do not work well. There are things they want to customize. From simple things like adding their own logo, having their own users, to more complicated things like defining their own workflows, adapting to their local regulations (imagine a web store, a community have to adapt it to their own local payment system).

So of course some of this modularity is something you would want also for your individual app. But my experience and user story is from communities. They have different structures, different ways to decide things, to run things, but often they need similar, but not exactly the same, features. So I am searching for a way to deliver that to them. That they could just click and get those features, adapt to their community, and then as a community use it.

**Comment by kentonv** [comment] 2015-06-19 21:38
> But currently your apps target single users, no?

No. There is a single _owner_, but we have a sharing model which you can use to share and collaborate with others, set permissions, etc. It would work great for a forum app, although we don't have such an app currently.

**Comment by mitar** [comment] 2015-06-24 10:34
> It would work great for a forum app, although we don't have such an app currently.

Then you might want to [update documentation](https://github.com/sandstorm-io/sandstorm/wiki/Packaging-Guide#what-makes-a-good-sandstorm-app). :-)

> Large discussion forums (although a federated forum where each user owns the threads they created could make sense).

**Comment by kentonv** [comment] 2015-06-26 22:17
Forum apps are sort of in a gray area. If it's a forum with tens of thousands of users or more then Sandstorm may not be a great fit. If it's a forum for a small group, like 5-100 users, then Sandstorm ought to work quite well.

**Comment by paulproteus** [comment] 2016-05-06 22:11
Hi @mitar,

I figure I should either:

- close this, since the issue is mostly discussion of what sorts of apps are good fits for Sandstorm, and how to properly package apps like WordPress or MediaWiki, or

- leave it open, until we write docs on this hypothetical "app addons" concept that we can point people to.

My personal preference is to close it for now, since app addons are a distant feature that we haven't fully specified yet, and I think we haven't evaluated other options against Kenton's proposed design.

So I'll close it, given that I think your original question got answered, and there wasn't a specific technical change requested here, but if you feel otherwise, please let me know.

**Closed by paulproteus** 2016-05-06 22:11 UTC

**Comment by jibe-b** [comment] 2016-10-23 11:06
Though this issue is closed I'd like to tell that app plugins is a feature I would really like to see achieved!

**Comment by zeigerpuppy** [comment] 2016-11-10 04:09
I agree, this would be a good feature.  There are enough apps that have plugins that it would be good to have some general mechanism to implement this function.
Many apps can download plugins from a repository but they cannot access external links from within sandstorm.
Maybe the simplest implementation would be a local davros instance where plugins can be added to directories for each application and those URLs then exposed to the apps.
At least, this would allow a tested set of plugins to be available using fairly standard interfaces.
