### ISSUE TITLE
In App Market pages screen shots are too small

### ISSUE THREAD

**Issue by paragjoshi** [sandstorm-io/sandstorm#2224] opened 2016-07-15 16:40 UTC
and there is no way to make the image bigger. Several screenshots are not readable. Check Apache Wave

**Comment by ocdtrekkie** [comment] 2016-07-15 16:43
If you look at Davros, you'll see that clicking on the screenshot does actually make it bigger. So the issue is that Apache Wave's screenshots are not large.

(As a side note, you can file bugs directly against the app market at https://github.com/sandstorm-io/sandstorm-app-market)

**Comment by paragjoshi** [comment] 2016-07-15 17:02
OK. Thank you for a quick response!

**Comment by ocdtrekkie** [comment] 2020-01-16 20:28
Closing this since the issue here was just that certain apps presented very small screenshots.

**Closed by ocdtrekkie** 2020-01-16 20:28 UTC
