### ISSUE TITLE
/ekam-provider/canonical/sandstorm/run-bundle.c++:1220: failed: unshare(CLONE_NEWUSER): Invalid argument

### ISSUE THREAD

**Issue by Dieterbe** [sandstorm-io/sandstorm#246] opened 2015-02-08 00:40 UTC
I run Arch Linux and followed the instructions, i.e.
```
curl https://install.sandstorm.io > install.sh
bash install.sh
```

install seems to have worked, but it fails with an error, see bottom of the output below.

```
~ ❯❯❯ curl https://install.sandstorm.io > install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18930  100 18930    0     0  67426      0 --:--:-- --:--:-- --:--:-- 67607
~ ❯❯❯ vim install.sh
~ ❯❯❯ bash
dieter@dieter-t420s ~  bash install.sh 
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
If you plan to use this Sandstorm instance for app development, you will need
to install Sandstorm as root, because Linux does not yet support mounting
FUSE filesystems in a UID namespace. Otherwise, you can install and run it as
a regular user. Even if installed as root, the main server processes will
never run as root. Either way, Sandstorm runs inside a directory you choose
and will not mess with the rest of your system.
Install as root? [yes] no
Where would you like to put Sandstorm? [/home/dieter/sandstorm] 
Server main HTTP port: [6080] 
Database port (choose any unused port): [6081] 
Expose to localhost only? [yes] 
Note: local.sandstorm.io maps to 127.0.0.1, i.e. your local machine. For
reasons that will become clear in the next step, you should use this
instead of 'localhost'.
URL users will enter in browser: [http://local.sandstorm.io:6080] 
Sandstorm requires you to set up a wildcard DNS entry pointing at the server.
This allows Sandstorm to allocate new hosts on-the-fly for sandboxing purposes.
Please enter a DNS hostname containing a '*' which maps to your server. For 
example, if you have mapped *.foo.example.com to your server, you could enter
"*.foo.example.com". You can also specify that hosts should have a special
prefix, like "ss-*.foo.example.com". Note that if your server's main page
is served over SSL, the wildcard address must support SSL as well, which
implies that you must have a wildcard certificate. For local-machine servers,
we have mapped *.local.sandstorm.io to 127.0.0.1 for your convenience, so you
can use "*.local.sandstorm.io" here. If you are serving off a non-standard
port, you must include it here as well.
Wildcard host: [*.local.sandstorm.io:6080] 
If you want to be able to send e-mail invites and password reset messages, 
enter a mail server URL of the form 'smtp://user:pass@host:port'.  Leave 
blank if you don't care about these features.
Mail URL: [] 
Automatically keep Sandstorm updated? [yes] 

Config written to /home/dieter/sandstorm/sandstorm.conf.
Finding latest build for dev channel...
Downloading: https://dl.sandstorm.io/sandstorm-65.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.2M  100 17.2M    0     0  5818k      0  0:00:03  0:00:03 --:--:-- 5819k
Setup complete. To start your server now, run:
  /home/dieter/sandstorm/sandstorm start
It will then run at:
  http://local.sandstorm.io:6080
To learn how to control the server, run:
  /home/dieter/sandstorm/sandstorm help
dieter@dieter-t420s ~  /home/dieter/sandstorm/sandstorm help
Usage: /home/dieter/sandstorm/sandstorm [<option>...] <command> [<arg>...]

Controls the Sandstorm server.

Something not working? Check the logs in SANDSTORM_HOME/var/log.

Commands:
  continue     For internal use only.
  dev          For internal use only.
  devtools     Install Sandstorm devtools.
  minibox      Command-line sandboxing tool.
  mongo        Run MongoDB shell.
  reset-oauth  Resets OAuth configuration.
  restart      Restart Sandstorm server.
  spk          Manipulate spk files.
  start        Start the sandstorm server.
  start-fe     Undo previous stop-fe.
  status       Check if Sandstorm is running.
  stop         Stop the sandstorm server.
  stop-fe      Stop the sandstorm front-end.
  supervise    For internal use only.
  update       Update the Sandstorm platform.

See '/home/dieter/sandstorm/sandstorm help <command>' for more information on a specific command.

Options:
    --verbose
        Log informational messages to stderr; useful for debugging.
    --version
        Print version information and exit.
    --help
        Display this help text and exit.
dieter@dieter-t420s ~  /home/dieter/sandstorm/sandstorm start
*** Uncaught exception ***
/ekam-provider/canonical/sandstorm/run-bundle.c++:1220: failed: unshare(CLONE_NEWUSER): Invalid argument
stack: 0x51b0e1 0x45684a 0x4b06b2 0x4ba747 0x4ba669 0x4ba65a 0x4596e1 0x45a365 0x51bd8a 0x4578dc 0x499552 0x5e9c80 0x401b87
dieter@dieter-t420s ~  
```

**Comment by dwrensha** [comment] 2015-02-08 00:46
I think this is a dupe of https://github.com/sandstorm-io/sandstorm/issues/162.

**Comment by kentonv** [comment] 2015-02-08 06:58
Indeed, sorry, this is because Arch Linux compiles the kernel without support for user namespaces (a key sandboxing feature).

We should probably improve the installer script to detect this.

Closing in favor of #162.

**Closed by kentonv** 2015-02-08 06:58 UTC
