### ISSUE TITLE
Grain Management UI

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1915] opened 2016-04-27 16:35 UTC
**Required to ship:**
Grain list:
- [ ] Grains archived will have an archive icon, grains trashed will have a trash icon. These will be displayed somewhere along each grain name.
- [ ] "Delete permanently" button should be disabled unless the grain is trashed. Only trashed grains can be permanently deleted.
- [ ] Disabled "Delete permanently" button will display a tooltip saying something like "Only trashed grains can be permanently deleted. Please trash the selected grains."
- [ ] Any grain can be archived or trashed; if at least one of the grains selected is already currently in the same archived or trashed state, we still allow the user to click the "Archived" or "Trash" button.
- [ ] Ability to select all and deselect all
- [ ] Search searches all lists: main list, archived, trashed.
- [ ] Trashed items have a 30-day expiry? We should also display a message above the grain list saying trashed grains that they will expire after 30-days. Perhaps a good time would be immediately after a user moves a grain to trash, or when they filter & view only trashed grains.

Grain view(opening a grain):
- [ ] If the grain is trashed by the owner/upstream, the owner sees an error: "File is in the trash, to access this grain restore it to the main list." Followed by primary button "Restore to main list" and secondary button "Go back to grain list"
- [ ] If the grain is trashed by the owner/upstream, the sharee sees an error: "You can no longer access this grain as it is in someone's trash." Followed by primary button "Go back to grain list".
- [ ] If the grain is deleted by the owner/upstream, the owner and sharee see an error: "No grain found with ID...". Followed by primary button "Go back to grain list".
- [ ] If grain is trashed/deleted grain preview will not display, top bar actions will not display.

**Out of scope:**
Grain list:
- keyboard shortcuts

Grain view:
- enabling sharees to request the owner to restore a grain
- advanced search operators
- labels/tags

Here's a preliminary mock-up so far:
![grain-mgmt3](https://cloud.githubusercontent.com/assets/855341/14897235/06e828ae-0d36-11e6-901b-2e8767c2f60e.png)
![grain-mgmt5](https://cloud.githubusercontent.com/assets/855341/15001527/14991ede-114d-11e6-872c-db705c2cf7ba.png)

Previous mock-ups:
[v1](https://cloud.githubusercontent.com/assets/855341/14859715/4df1bad0-0c5a-11e6-93ff-c7bbdb30c1d5.png)
[v2](https://cloud.githubusercontent.com/assets/855341/14897264/2d6d75e2-0d36-11e6-9147-8acca4b95f8a.png)
[v2](https://cloud.githubusercontent.com/assets/855341/14865838/848ae5e2-0c75-11e6-9e19-3ab637fc1432.png)
[v3 - trash](https://cloud.githubusercontent.com/assets/855341/14897645/d06c6716-0d37-11e6-97c6-2ec6195afc38.png)

Notes: 
Main list: grains that are not archived / trashed
Archive is for organization purposes, does not affect how others view it.
@zarvox probably has some things to add.

**Comment by dwrensha** [comment] 2016-04-27 17:01
I think "trashed" carries connotation we don't want. Maybe "remove" / "removed" would work better than "trash" / "trashed".

I'm also worried about the distinction between deleting a grain you own and forgetting a grain that someone else has shared with you. Could it possibly make sense to use "remove" in both of these cases?

**Comment by ocdtrekkie** [comment] 2016-04-27 17:05
But "Trash", like "Recycle Bin", indicates you are not actually deleting something (like "Remove" often does. People may not realize that "Remove" doesn't actually delete anything.

**Comment by dwrensha** [comment] 2016-04-27 17:09
Maybe the button could be "move to trash" and the filter checkbox could be "trash" (as a noun). But I'm still worried that "move to trash" might be confusing for "shared with me" grains.

**Comment by ocdtrekkie** [comment] 2016-04-27 17:11
@dwrensha Here's a question: Is there potential value in allowing me to "Trash" a grain "Shared With Me"? As in, that my link to that grain is in my Trash, and I can undo it and get it back?

**Comment by dwrensha** [comment] 2016-04-27 17:12
@ocdtrekkie: you tell me. Is that a feature you want?

**Comment by ocdtrekkie** [comment] 2016-04-27 17:14
I could see accidentally deleting a grain link to someone's private grain accidentally just as much as accidentally deleting one of my own grains. Depending on the grain, it could be difficult to get the capability back (dude's on vacation or something, I don't know).

_And_, unlike my own trashed grains, which I presume still count against my storage, there's basically no downside to leaving a grain shared with me in my trash.

**Comment by paulproteus** [comment] 2016-04-27 17:15
I might sound like I'm sarcastic, but I mean this earnestly: I don't know
what connotation "Trashed" has that we don't want.

I also agree with ocdtrekkie that "Remove" is hard to understand as
reversible.

I also agree with dwrensha that hard to understand that "Trash" a shared
grain doesn't actually trash it for the owner.

**Comment by ocdtrekkie** [comment] 2016-04-27 17:16
@paulproteus I assume the poor connotation of a "trashed grain" would be much like if I "trashed my dining room". Could be messy, corrupted, dirty, of poor quality, etc.

**Comment by ocdtrekkie** [comment] 2016-04-27 17:22
I think it should be understandable that your trash is your trash, for your list. Aka, trashing a "shared with me" grain doesn't remove it from the actual owner.

Though, viable question: How will Sandstorm handle shared access to your grains when you archive them or trash them? I would assume archiving a grain I shared with someone would not disable their access, but trashing a grain I shared with someone would.

As a note, if I delete a shared folder in Windows, I get a popup telling me that the folder is a shared folder, and deleting it will cause everyone to lose access to it. This might be a useful warning for grain owners when they trash a grain.

**Comment by neynah** [comment] 2016-04-27 19:11
So, we've decided to table "archived" for now since there's further discussion that needs to be made regarding archivs, labels, folders, etc.

After an in-person discussion there's concensus that "Trash" is acceptable and accurate but the word "Trashed" has a poor connotation as mentioned above. I've updated the notes above so that we're using the noun "Trash" rather than the adjective "Trashed". I'll update the mock-up shortly!

**Comment by zarvox** [comment] 2016-04-27 21:24
To clarify some intended behavior discussed above:

* Grains placed in their owner's trash cannot be started.
* ApiTokens (aka sharing links) placed in their owner's trash do not transfer permissions to their children.
* If you attempt to open a grain which is in your trash, you should see a message that the grain cannot be opened while in the trash and a button to move it out of the trash and start it.

**Comment by zarvox** [comment] 2016-04-27 21:42
@neynah We probably shouldn't have the tabs and the action buttons in the same row, particularly if they're changing presence/absence.

**Comment by neynah** [comment] 2016-04-27 22:00
@zarvox The only other reasonable place I can think of is having the grain actions directly above the tabs but that's not super appealing to me as I think the grain actions should be directly above the grain list. Perhaps there is a better way we can display the "main list" tab and the "trash" tab.

**Comment by ocdtrekkie** [comment] 2016-04-27 22:53
What about rather than tabs, having a "View Trash" button, and a "Back" button on the Trash tab? Then rather than tabs, you just have all actions?

**Comment by neynah** [comment] 2016-04-28 00:29
@ocdtrekkie I think there was a concern about it being unclear as to which set of grains were currently being viewed(without tabs). Perhaps that's solved with a title saying "Main list" with a button that says "View Trash" and vice versa as you're suggesting. We would need to be careful not to style the "View Trash" button similarly to the other actions that are grain actions though.

**Comment by ocdtrekkie** [comment] 2016-04-28 00:31
I feel like a tab alongside the main list is too high level for your trash. It's a folder you'll rarely if ever go to.

**Comment by neynah** [comment] 2016-04-28 18:54
Thanks for the feedback every one. I've updated the mock-ups above once again. I've removed the need for tabs and just added a "View Trash" button and "View Main list" button. Each grain that is in the trash also has a clear trash icon beside it.

**Comment by paulproteus** [comment] 2016-04-28 20:12
@neynah & all, thanks for doing all this mocking-up and revising.

As random commenter, I will add that I would prefer that the button labeled "Trash" were labeled "Move to Trash", since I was a little confused about what clicking it does. I'm already +1 to these changes as-is; my remark is not intended to be showstopper-level.

**Comment by paulproteus** [comment] 2016-04-28 20:13
As a side note about timeline:

- @dwrensha has been working on this for the past few days already, and

- I believe the goal is to ship this in the next 1-2 weeks, preferably even sooner.

**Comment by ocdtrekkie** [comment] 2016-04-28 20:17
I am +1 on "Move to Trash".

And I am doubly +1 on such a near time frame!

**Comment by neynah** [comment] 2016-04-28 20:20
@paulproteus I think "Move to Trash" is an improvement. :)

@zarvox Should this "Move to Trash" button be disabled until a user selects at least 1 grain?

**Comment by dwrensha** [comment] 2016-04-28 20:21
Yeah, I'm disabling the bulk action items when nothing is selected.

**Comment by neynah** [comment] 2016-04-28 20:23
Cool. I guess we'll also want to add a tooltip on the disabled button saying something similar to "Select a grain then move it to trash".

**Comment by neynah** [comment] 2016-05-03 23:35
@dwrensha I updated the trash list UI in the mock-up above to show additional help text and a "Days remaining" column. "Days remaining" is more valuable & digestible for the user than "Date moved to trash" but perhaps "Days remaining" should be implemented in the future & not for the first version.

**Comment by paulproteus** [comment] 2016-05-03 23:36
I'm +1 on "Days remaining" being more meaningful over "Date moved to
trash", fwiw.

**Comment by dwrensha** [comment] 2016-05-09 20:20
As brought up on #1841, we probably need to update the billing prompt that comes up when you reach quota. Currently it looks like: 
<img width="698" alt="out-of-storage" src="https://cloud.githubusercontent.com/assets/495768/15126802/d18c918e-1601-11e6-9063-c0a4f2e4293b.png">

I suppose we should update the text in the lower right and add an "empty trash" button. @neynah: what should this look like?

**Comment by neynah** [comment] 2016-05-09 20:31
@dwrensha I'm not sure if we want to add a "empty trash" button there since the user can't actually see what's in the trash. Also, if they don't have anything in the trash then that button is also not useful for them.

Perhaps we can replace the first 2 lines of text "If you run out of space, you'll need to delete one of your existing grains before you can create a new one. Open a grain and click _ in the top bar." with:
"If you run out of space, you'll need to trash then permanently delete at least one of your existing grains before you can create a new one. [Visit your grain list to trash then permanently delete grains>>](https://oasis.sandstorm.io/grain)"

**Comment by dwrensha** [comment] 2016-05-16 19:52
Closing because this has shipped. Further refinements or bug reports should go in separate issues.

**Closed by dwrensha** 2016-05-16 19:52 UTC
