### ISSUE TITLE
feature request: copy a grain

### ISSUE THREAD

**Issue by kingemir** [sandstorm-io/sandstorm#2773] opened 2016-11-25 07:51 UTC
The alternative of downloading and uploading a grain is too cumbersome, too time-consuming, and generates unnecessary data traffic

**Comment by neynah** [comment] 2016-11-29 00:41
Thanks for the suggestion!

Could you tell us more about in which situations you would want to copy a grain? Also, it sounds like downloading an upgrading a grain is currently a painful process for you- how often do you find yourself doing this? Would copying multiple grains at once also be useful?

**Comment by kingemir** [comment] 2016-11-29 18:56
I create technical reports with sharelatex. These reports have always the same layout and structure. I reuse the same latex project every time I write a new report and just modify some content, as measurement data, names of customers, logo, conclusion etc. Sharelatex.com provides the feature of copying a latex project:
![bildschirmfoto 2016-11-29 um 19 43 25](https://cloud.githubusercontent.com/assets/19539230/20723814/4a04fc90-b66c-11e6-9ec3-07a5ad697a29.png)
but sandstorm.io doesn't

I also create technical graphics using draw.io, i.e. flowcharts, for different projects. They also follow always the same principle and style, just some content is replaced. www.draw.io allows to open a template file: 
![bildschirmfoto 2016-11-29 um 19 47 57](https://cloud.githubusercontent.com/assets/19539230/20723973/dcb2fc0e-b66c-11e6-92b4-eee873f32ce6.png)
but sandstorm.io doesn't


I also create different versions of a website with Hakyll CMS, with the purpose of my customer being able to compare them before the site's published. 

It's very common to work with templates or with variations of a product/project. 

Downloading and uploading a grain doesn't always work smoothly, it depends on the internet connection and the hardware system on both user and server side. Sometimes it's stuck, sometimes you have to wait and wait until it's done, and it's a lot of work to do: clicking, navigating, clicking, navigating... and it's also stupid to generate data traffic between distant instances when I just want to copy data from sandstorm.io to sandstorm.io

See also the discussion on https://groups.google.com/forum/#!msg/sandstorm-dev/mAPOuHWFIuQ/eNQOlYuvBQAJ

**Comment by zeigerpuppy** [comment] 2016-11-30 02:46
I agree that especially for sharelatex, cloning a grain would be really useful.  Many people keep template documents in sharelatex and then copy these out for new docs.  In general I think it's also more intuitive for the users to clone rather than backup/restore backup.

**Comment by ocdtrekkie** [comment] 2020-03-07 19:24
This is a duplicate of #1703

**Closed by ocdtrekkie** 2020-03-07 19:24 UTC
Labels: enhancement, usability
