### ISSUE TITLE
Some apps fail to run

### ISSUE THREAD

**Issue by jvasile** [sandstorm-io/sandstorm#1694] opened 2016-03-23 20:57 UTC
I installed Sandstorm today and all is well for many apps.  Others just fail to work right out the gate.  Telescope and Groove Basin both load an initial screen and then keep refreshing or reloading forever without end.  When I hit the debug log, I see the same line over and over: { type: 'sandstorm', userId: 'randomstring' }

Maybe this is an implementation bug or maybe it's a config problem on my end, but it's definitely a UX fail.  I was left without much ability to hunt down the error.

**Comment by dwrensha** [comment] 2016-03-23 20:59
Hmm. This sounds like what happens when websockets aren't working for some reason.

**Comment by paulproteus** [comment] 2016-03-23 21:28
It could be that now is a good time to figure out how to integrate "maaan
your websockets are broken" into a message kind of like the admin warning
that complains about wildcard DNS. I could possibly be the person to write
that.

**Comment by jvasile** [comment] 2016-03-23 22:08
It might be useful to test web sockets upon initial install, the same way wildcard sub domains get tested.

I'm not sure where websockets enter the picture, but here's another data point in case it helps: I'm running Sandstorm on a box that sits behind a reverse proxy located on a different box.  The box running Sandstorm can make outgoing connections to the Internet but is firewalled against incoming connections except those coming from the reverse proxy.  The broken web sockets issue might be related to this.

**Comment by paulproteus** [comment] 2016-03-23 22:54
Hi @jvasile ,

I suppose there are at least two things to find out here.

First, how can we solve your immediate problem?

Second, how can we help people like you solve this problem without having to get in touch with us?

I'll work on the first right now, and turn the second into a separate GitHub issue.

**Comment by paulproteus** [comment] 2016-03-23 22:56
If you're using a reverse proxy, which you say you are, is it nginx? If so, note that you'll need a stanza like:

```


# This magic stanza is ESSENTIAL to avoid breaking WebSockets.
#
# Specifically, for WebSocket forwarding, we want to forward the `Connection` header.
# This "map" declaration helps with that.
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}
```

in your nginx settings. See also: https://github.com/sandstorm-io/sandstorm/blob/master/docs/administering/sample-config/nginx-example.conf & https://docs.sandstorm.io/en/latest/administering/reverse-proxy/

If your reverse proxy is Apache2, then I am honestly not yet sure how to enable WebSockets while reverse proxying. Let me know which you're using, and we can figure things out.

**Comment by paulproteus** [comment] 2016-03-23 22:56
For nginx, you'll also need something like:

```
  location / {
    proxy_pass http://127.0.0.1:6080;

    # Forward the Host header, which is used to route requests for
    # static content published from Sandstorm apps.
    proxy_set_header Host $http_host;

    # Forward WebSocket.
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
```

**Comment by paulproteus** [comment] 2016-03-23 23:05
Ah hah, apologies - you mentioned what kind of reverse proxy:

> Apache reverse proxy

I _believe_ (but have not yet been able to test) that the following should help you get websockets forwarding enabled for Sandstorm:

Your server config probably has a stanza like:

```
<VirtualHost *:80>
  ServerName www.domain2.com

  ProxyPassReverse / http://sandstorm.internal:3001/
</VirtualHost>

```

You need to modify it so that it is willing to pass `/` to two different URLs, which it will choose between.

```
<VirtualHost *:80>
  ServerName www.domain2.com

  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket
  RewriteRule /(.*)           ws://sandstorm.internal:3001/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket
  RewriteRule /(.*)           http://sandstorm.internal:3001/$1 [P,L]

  ProxyPassReverse / http://sandstorm.internal:3001/
</VirtualHost>
```

I believe that should be enough. However, I haven't been able to verify this experimentally yet, so I'd love your help.

**Comment by paulproteus** [comment] 2016-03-23 23:24
@jvasile In my local testing I'm able to reproduce this problem. Here's my apache2 config:

```
<VirtualHost *:80>
  RewriteEngine On
  ProxyPass / http://localhost:6080/
  ProxyPreserveHost On
</VirtualHost>
```

I'll now see if I can provide a config that does work.

**Comment by paulproteus** [comment] 2016-03-23 23:28
This is a config that makes the problem go away. @jvasile can you test something like this in your environment?

```
<VirtualHost *:80>
  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket
  RewriteRule /(.*)           ws://localhost:6080/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket
  RewriteRule /(.*)           http://localhost:6080/$1 [P,L]
  ProxyPass / http://localhost:6080/
  ProxyPreserveHost On
</VirtualHost>
```

Note that, on Debian, for this to work, I had to also run:

```
sudo a2enmod proxy_http
sudo a2enmod proxy_wstunnel
sudo a2enmod rewrite
```

**Comment by paulproteus** [comment] 2016-03-23 23:28
If this works for you, then I will be very happy to hear so, and will add it to our docs.

**Comment by paulproteus** [comment] 2016-03-23 23:54
https://docs.sandstorm.io/en/latest/administering/faq/#how-do-i-enable-websockets-proxying-or-why-do-some-apps-seem-to-crash-reload is a link to the new docs on this.

**Comment by jvasile** [comment] 2016-03-23 23:55
Asheesh, it's working for me now.  Groove Basin, Rocket.Chat and Telescope were the three apps that previously failed and now appear to function.  At least, the app loads.  I haven't tested beyond that.

Here's what I have in my sites-enabled/sandstorm:

     <VirtualHost *:80>
         ServerName sandstorm.jamesvasile.com
         ServerAlias *.sandstorm.jamesvasile.com

         RewriteEngine On
         RewriteCond %{HTTP:Upgrade} =websocket
         RewriteRule /(.*)           ws://barium:6080/$1 [P,L]
         RewriteCond %{HTTP:Upgrade} !=websocket
         RewriteRule /(.*)           http://barium:6080/$1 [P,L]

         ProxyPreserveHost On
         ProxyPass / http://barium:6080/
         ProxyPassReverse / http://barium:6080/
</VirtualHost>

I have proxy_http, proxy_wstunnel, and rewrite enabled.  The box "barium" is firewalled but available via a VPN.

The ServerName line tells Apache the name of the server (sandstorm.jamesvasile.com) and the ServerAlias line enables the wildcard subdomains that Sandstorm relies on.  If you omit it, the Apache server will send requests to foo.sandstorm.jamesvasile.com to the default virtual host.

I don't know that "ProxyPassReverse" is necessary.  It depends on whether Sandstorm ever does redirects.  It won't do any harm, though, so I usually do ProxyPass and ProxyPassReverse together when setting up proxies.

Thanks for the attentive response.  Investigating Sandstorm has been on my todo list for a month or two, and I'm impressed by how easy it is to get it working.  Toss that Apache stanza in the docs and even my minor speedbump will be a one-off.

**Comment by paulproteus** [comment] 2016-03-24 01:54
Great! I'll close this issue now, since the support aspect of it is addressed, and work on the automatic notification in a separate issue. If you run into any further problems, @jvasile , please feel free to let me know!

**Closed by paulproteus** 2016-03-24 01:54 UTC
