### ISSUE TITLE
Cannot install libreboard, error while downloading

### ISSUE THREAD

**Issue by wascrum** [sandstorm-io/sandstorm#704] opened 2015-08-21 10:00 UTC
hello,
I have a virtual machine with ubuntu 14.04 and sandstorm installed. When I want to install the app 'libreboard' the following error occours:

"Failed to install app!
getaddrinfo ENOTFOUND"

Log says following:
"...** Starting Sandstorm at: Thu Aug 20 15:13:38 2015
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 7
child process started successfully, parent exiting
[object Object]
Successfully added user: {
	"user" : "sandstorm",
	"roles" : [
		"readWriteAnyDatabase",
		"userAdminAnyDatabase",
		"dbAdminAnyDatabase"
	]
}
** Back-end and Mongo started; now starting front-end...
WriteResult({ "nRemoved" : 0 })
Migrations applied: 0/6
Applying migration 1
Applied migration 1
Applying migration 2
Applied migration 2
Applying migration 3
Applied migration 3
Applying migration 4
Applied migration 4
Applying migration 5
Applied migration 5
Applying migration 6
Applied migration 6
Admin token deleted.
Downloading app: http://git.libreboard.com/libreboard/releases/raw/master/0.8.0/libreboard.spk
Failed to install app: Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
Downloading app: http://git.libreboard.com/libreboard/releases/raw/master/0.8.0/libreboard.spk
Failed to install app: Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
** Updater died; restarting it
...
** Updater died; restarting it"

Can someone help me with this? Maybe a dns problem? We are behind a firewall.
Is there a way to download the files manually and put it in sandstorm?

**Comment by paulproteus** [comment] 2015-08-21 10:03
Hi! One thing you can do is manually download the SPK (since you have the
URL) and use "Upload an app" to upload it from your own computer.

You might find the ENOTFOUND error goes away if you restart Sandstorm,
also, since it copies /etc/resolv.conf into its container at the time it
starts.

If you need HTTP proxy support, that's something we're working on. See
https://github.com/sandstorm-io/sandstorm/issues/693 for the status of that
(summary: we know it's important, but no ETA quite yet).

**Comment by wascrum** [comment] 2015-08-21 11:16
thanks for your anwser, I tried it with "Upload an app". 

First try aborted at 98% with error from the first post:
""Failed to install app!
getaddrinfo ENOTFOUND""

but Libreboard was bizarrely in the menu. If I created a new board, it stuck at loading.
Because of that I reinstalled it, at the second try the installation was successful.
But the same again, when I start a new board, it loads and loads and loads.

I restartet the server and sandstorm, no effect.


Libreboard Log says:
"...** SANDSTORM SUPERVISOR: Starting up grain.
sandstorm/supervisor.c++:1144: warning: ip_tables kernel module not loaded; cannot set up transparent network forwarding.
** Starting Mongo...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 6
all output going to: /var/mongo.log
child process started successfully, parent exiting
** Starting Meteor...
Meteor._wrapAsync has been renamed to Meteor.wrapAsync
> Starting board-background-color migration.
> Finishing board-background-color migration.
> Starting lowercase-board-permission migration.
> Finishing lowercase-board-permission migration.
> Starting change-attachments-type-for-non-images migration.
> Finishing change-attachments-type-for-non-images migration.
> Starting card-covers migration.
> Finishing card-covers migration.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now."



Sandstorm Log says repeatedly:
"Exception while invoking method 'keepSessionAlive' Error: remote exception: grain is not running
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:395:16)
    at [object Object].Meteor.methods.keepSessionAlive (app/server/proxy.js:222:14)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    at packages/ddp/livedata_server.js:546:1
    - - - - -"


I dont know if its a problem with sandstorm/libreboard or my machine/network. Some suggestions what I can do?

**Comment by paulproteus** [comment] 2015-08-25 23:07
"Loads and loads and loads" sounds like a similar issue as https://github.com/sandstorm-io/sandstorm/issues/708 -- do you think your situation is also a WebSockets configuration problem, perhaps? If so, there's some advice in that issue on how to fix that.

Let me know if you succeed, and let me know if you need more help!

**Comment by zarvox** [comment] 2015-11-05 20:58
I believe that I have identified the root cause of this issue and that it is fixed by #1097.  Feel free to reopen or file a new bug if you're still having trouble!

**Closed by zarvox** 2015-11-05 20:58 UTC
