### ISSUE TITLE
Mongodb setting config

### ISSUE THREAD

**Issue by Bianconiglio** [sandstorm-io/sandstorm#3468] opened 2020-11-13 16:34 UTC
Hi,
where i find the config file for change settings about mongodb database?

I want use a remote mongodb database.

there is a script for re-create database in remote mongodb?

**Comment by ocdtrekkie** [comment] 2020-11-13 16:57
I don't think anyone has ever tried to use a remote database with Sandstorm. By design, Sandstorm sort of self-containerizes in the /opt/sandstorm directory.

**Comment by zenhack** [comment] 2020-11-13 21:25
Yeah, we don't support using an external database. Sandstorm starts mongo as part of it's own startup, and it's not possible to configure it to use an already-running db instead. Sorry.

**Comment by Bianconiglio** [comment] 2020-11-13 22:29
if I understand correctly the mongodb database contains user configurations, if it were possible to use an external mongodb it would be possible to share the configurations of multiple servers with sandstorm.

if there were many users using sandstorm on one server, it would not be possible to use multiple servers to decrease the workload

scaling the traffic horizontally would be very interesting

**Comment by ocdtrekkie** [comment] 2020-11-14 00:35
There is actually a version of Sandstorm that scales a bit like that. It's called Blackrock, although it is pretty bitrotted right now. It is designed to have various components of Sandstorm distributed over multiple machines.

However, in practice, Sandstorm never had a server under enough load for this to be needed. The service that ran using Blackrock, Oasis, could've functioned as a single large server successfully.

I am going to go ahead and close this, since this would be a unsupported thing to do, but if you are really interested in a Sandstorm platform that scales that large, you could look at Blackrock.

**Closed** 2020-11-14 00:35 UTC
Labels: install-config, question

**Comment by zenhack** [comment] 2020-11-14 04:05
The stand-alone version of Sandstorm is really designed around being a "turn-key" solution, and I think we want to move more in that direction, someday handling the whole install process including the OS. Most folks who are active in the community have single machine installs (often attached to residential ISPs...). There's not a lot of active interest in the community in larger scale deployments.

Note that it would take more than just pointing Sandstorm at an external mongo instance to have multiple servers handling a single logical Sandstorm "instance;" while the javascript bits of the code are largely capable of this, the C++ code that manages the grain lifecycle & storage has more of an expectation of running on a single machine. So separating out the DB might be nice for redundancy reasons for the DB itself, but it wouldn't be enough to horizontally scale Sandstorm.

As @ocdtrekkie mentions there was an alternate backend for Sandstorm called Blackrock (the repo for it is still available), but note that it was designed for "elastic compute" platforms, not merely multi-server setups, and it is somewhat tied to Google's offering -- in principle the relevant code is pluggable, so one could write backends for e.g. openstack, but nobody has actually done so -- Sandstorm Oasis was the only user of blackrock, and so there wasn't really demand for this until Sandstorm-the-business shut down and threw the code over the wall, and blackrock has been unmaintained since. I can't actually think of anything off the top of my head that we've done that "should" break blackrock, so it's possible it still works I suppose, but I wouldn't count on it, since nobody's been testing or maintaining it.

**Comment by ocdtrekkie** [comment] 2020-11-14 04:43
IIRC Blackrock was already being pinned to an old version because of an issue, so I would assume that at minimum is outstanding.

**Comment by Bianconiglio** [comment] 2020-11-14 10:31
thank you so much for all help and for information, sandstorm it's a really interesting software.
