### ISSUE TITLE
sandstorm-http-bridge sometimes consumes lots of RAM

### ISSUE THREAD

**Issue by mrdomino** [sandstorm-io/sandstorm#1600] opened 2016-02-27 01:52 UTC
Currently it's using 659.7MB on my instance. It's been probably a day since I last restarted, and the only thing that stands out to me as unusual about usage today is that people have been uploading a bit more music than usual to my groovebasin. Also I've been streaming and previewing songs a bit more than usual.

**Comment by paulproteus** [comment] 2016-02-27 01:53
BTW, how many sandstorm-http-bridge processes are there? Do you know which
grain is associated with the big one(s) of them?

**Comment by mrdomino** [comment] 2016-02-27 01:56
I see 2. mrdomino radio is the big one by the looks of it.

**Comment by dwrensha** [comment] 2016-02-27 03:19
Possibly related to #1054.

**Comment by kentonv** [comment] 2016-03-05 00:38
Yes, I'm going to say this is definitely a dupe of #1054.

Probably the specific cause in @mrdomino's case is either:
a) Someone downloaded a huge file.
b) There was a dirty disconnect (i.e. TCP packets simply stopped being ACK'd) causing the stream to that user to buffer up for some time before finally the connection timed out and the whole thing canceled.

@mrdomino FWIW you can reset the RAM usage by restarting the app by hitting the "refresh"-looking button in the top bar. Of course, that'll disrupt everyone's streams.

**Closed by kentonv** 2016-03-05 00:38 UTC
