### ISSUE TITLE
While using a grain, but not looking at it for a while, I get "No such grain for public ID: (xyz) 404"

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#971] opened 2015-10-03 20:11 UTC
Steps to reproduce:

* Go to Oasis

* Create a WeKan board

* Switch tabs

* Don't look at the tab for about an hour

* Switch back to the tab with the WeKan board

Expected behavior:

* I see the WeKan board

Actual behavior:

* I see "No such grain for public ID: 43da8e73270f49ec1c2d94181e8a202e [404]" (attaching screenshot)

Other notes:

@dwrensha notes that https://github.com/sandstorm-io/sandstorm/pull/867 should have probably fixed this.

![no-such-grain](https://cloud.githubusercontent.com/assets/25457/10264916/4d8d43a2-69d0-11e5-99e7-09e34895d94a.png)

**Comment by jparyani** [comment] 2016-01-29 20:10
This is an old duplicate of #1335. Closing in favor of the newer issue.

**Closed by jparyani** 2016-01-29 20:10 UTC
