### ISSUE TITLE
Permanently deleting grain from trash should remove it from navbar

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#2659] opened 2016-10-15 00:11 UTC
To reproduce:

* Create a new grain of any app
* Click "Grains" in the navbar
* Check the checkbox for the grain you just created
* Click "Move to trash"
* Click "View trash"
* either empty the trash or select that grain and click "Delete permanently"

You will now have an item "(unknown grain)" with an identicon in the sidebar.  It would probably make more sense to close the sidebar items in the current window (which definitely does not have that view open), and possibly all other windows too if the grain was open anywhere else.

**Comment by jparyani** [comment] 2016-10-29 00:03
Closing as a duplicate of #1983. This one does have much better instructions for repro-ing, however it did come later :/

**Closed by jparyani** 2016-10-29 00:03 UTC
