### ISSUE TITLE
Sandstorm's IP changed

### ISSUE THREAD

**Issue by ClocxHD** [sandstorm-io/sandstorm#2173] opened 2016-07-03 17:35 UTC
Hello,

i moved my Sandstorm-VM into a different Subnet, therefore it has a new public ip address.
This happened about 4 hours ago, but the .sandcats.io-Domain doesn't changed.
It still has the old ip.
How can i force Sandstorm to update the dns records for the .sandcats.io Domain?

**Comment by kentonv** [comment] 2016-07-05 01:23
Hmm, this should happen automatically within a couple minutes. Is it at all possible that your server has outgoing UDP traffic to sandcats.io blocked?

**Comment by ClocxHD** [comment] 2016-07-05 07:10
The Firewall of the Server is disabled, therefore it should not block incoming/outgoing connections.

**Comment by zarvox** [comment] 2016-07-06 01:17
Maybe this is a problem with DNS resolution inside the run-bundle container?

Does the Sandstorm system log (`/opt/sandstorm/var/log/sandstorm.log`) contain a line like:

```
WARNING: /etc/resolv.conf is unreachable from container, using backup from host
```

Can you resolve `sandcats.io` from your server?  The output of running `host sandcats.io` from the server would help here.

Is your server's `/etc/resolv.conf` a file, or a symlink to some other file (`ls -l /etc/resolv.conf`)?  If the latter, where does it point?

Does restarting Sandstorm (`sudo service sandstorm restart`) fix things?  Does anything interesting get written to the Sandstorm log?

**Comment by ClocxHD** [comment] 2016-07-06 16:12
Hello,

thanks for the tip with the log!
The log said, that sandstorm cannot bind to the ip.
Then i looked at the config again, and saw, that there was a typo in the ip.
I corrected the ip, restarted sandstorm and no it works!
Thanks! :)

**Comment by zarvox** [comment] 2016-07-06 18:50
Great!  I'm glad you got things sorted out.

I'm curious what steps you took to debug this, and if we could have helped you find the config typo sooner.  Did you look in system logs, or the systemd journal, or manually try restarting sandstorm?  I could see any of those being places that we might have been able to surface the root cause sooner.

**Comment by gtrevg** [comment] 2016-07-07 15:42
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  gtrevg@gmail.com
    Domain plentyproductions.com has exceeded the max emails per hour (200/200 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:54651 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server21.abstractdns.com with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bLBS0-0003CE-Qf
	for github@trevorgattis.com; Thu, 07 Jul 2016 15:42:52 +0000
Date: Wed, 06 Jul 2016 09:12:03 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1467821523;
	bh=ElxPEwLfqQ8EYEMsI9PCrzDmdNqZtwCWMAZiesAJkWQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=IBPjD81ifvTixUeoc1Emj5hGRpCPAbhJgE3E47r4hiC6kKfkjsxdA5xoQN7bjzSJu
	 CCRC+sl2tiBTmlkz7ak1eRs9Ap7suQqJxgLyfW1zx2Sc7/CSyA5tUOa8id1HWZIW3w
	 iT+N2yhG7Agntyctq0n9D4wDkca8evQ12uJ2fNMM=

**Comment by zarvox** [comment] 2016-07-19 00:19
Since it sounded like the issue was resolved, I'm going to close this ticket.  Feel free to open a new ticket if you have any new troubles!

**Closed by zarvox** 2016-07-19 00:19 UTC
