### ISSUE TITLE
spk crash when spinning up vagrant-spk stack

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/sandstorm#1489] opened 2016-02-09 16:23 UTC
```
sandstorm/util.c++:55: failed: open(name.cStr(), flags, mode): No such device; name = /dev/fuse
stack: 0x4f5bef
*** Uncaught exception ***
sandstorm/send-fd.c++:90: failed: expected n > 0; premature EOF while waiting for FD
stack: 0x41fafc 0x41f2dd 0x4a526f 0x4a4d8a
Connection to 127.0.0.1 closed.
```

This is triggered by https://github.com/ndarilek/loomio-sandstorm. I haven't tried this build in months but it used to work fine-ish.

Thanks.

**Comment by paulproteus** [comment] 2016-02-09 16:26
For now, you can add:

sudo modprobe fuse

within your .sandstorm/build.sh


There's a bad system interaction aka Sandstorm bug, or arguably install.sh
bug, at the root of this. I guess it's time for me to fix it.

**Comment by paulproteus** [comment] 2016-02-09 16:27
See also https://github.com/sandstorm-io/sandstorm/issues/858 (which disables the fuse functionality if not present), but since you're doing `vagrant-spk dev` then we ought to provide a more useful error message and/or self-heal.

**Comment by paulproteus** [comment] 2016-02-09 16:35
Clarification: I hope to get to this sometime, but I don't know when, so if someone else on the Sandstorm team is motivated to look at it in the next few days, that'd be fantastic. Else I'll add it to my queue for Friday at least.

**Comment by ndarilek** [comment] 2016-02-10 03:41
When I `sudo modprobe fuse` in the linked Vagrant setup, I get this in 
dmesg:

```
[19796.488306] fuse: Unknown symbol sysfs_create_mount_point (err 0)
[19332.119232] fuse: Unknown symbol sysfs_remove_mount_point (err 0)
```

And the modprobe fails. Any thoughts?

**Comment by paulproteus** [comment] 2016-02-10 06:04
Wow, OK. That's some terrible version skew going on in the vagrant-spk base
box.

I'll dig into it tomorrow. Sorry for the difficulties you're running into.

**Comment by elimisteve** [comment] 2016-02-12 15:14
+1 for getting this fixed; sounds like there's a lot of activists who'd love to run Loomio on top of Sandstorm!

**Comment by samuk** [comment] 2016-02-12 15:50
Nothing to offer but a bit of encouragement. 

Thanks for working on this, there are indeed people interested in using it.

Thanks

Sam

**Comment by paulproteus** [comment] 2016-02-13 10:04
Hi @ndarilek ,

I think this has to do with a Debian kernel update that happened. I was able to reproduce the problem on my end.

I think if you do:

```
vagrant-spk ssh
```

and then run

```
sudo reboot
```

the problem goes away for me. Does it go away for you in that circumstance?

If so, we should figure out a deeper fix within `vagrant-spk`. It's helpful to know if this fixes it for you.

**Comment by paulproteus** [comment] 2016-02-13 10:07
**CORRECTION**

You should run:

```
vagrant-spk halt
vagrant-spk up
```

rather than the SSH stuff I said above. I manually tested the halt & up thing, and that also fixes/works around the issue for me.

(p.s. The reason `sudo reboot` doesn't do anything useful is that `vagrant` needs to control the start process so it can add network filesystem stuff.)

You can quickly verify that it got into a useable state by running:

```
sudo modprobe fuse
sudo lsmod | grep fuse
```

and seeing that `fuse` is in the `lsmod` output.

**Comment by paulproteus** [comment] 2016-02-13 10:08
For what it's worth, your `setup.sh` has `apt-get dist-upgrade -y` and if you don't run that command, you'll avoid this problem.

You probably can run

`apt-get upgrade -y`

instead, and get the desired results.

**Comment by paulproteus** [comment] 2016-02-16 05:49
@ndarilek I hope you'll let me know if the above hints have or haven't helped!

**Comment by ndarilek** [comment] 2016-02-16 14:10
Of course. Between 2 imminent product launches and other things, I just 
haven't had time to look at this recently.

**Comment by emanuelwiesner** [comment] 2016-02-17 14:15
@paulproteus - I am not using sandstorm - I am running "default" Debian 8 and have exactly the same issue as described AND I know it has something to so with a Debian kernel update

> I think this has to do with a Debian kernel update that happened. I was able to reproduce the problem on my end.

Would you please explain what you have done to reproduce/fix this? I already opened a thread on [stackexchange.com](http://stackoverflow.com/questions/35397318/error-could-not-insert-fuse-unknown-symbol-in-module-or-unknown-parameter), but we couldnt solve this... Thank you SO much!

**Comment by paulproteus** [comment] 2016-02-17 15:15
Hi there,

All I really know is:

- I did 'vagrant-spk up' and allowed Nolan's setup.sh scripts to
dist-upgrade the box

- This resulted in a state where 'modprobe fuse' gave me the error message
Nolan reported

- Then when I did 'vagrant-spk halt' then 'vagrant-spk up' the error
message was gone.

I presume this relates to a kernel upgrade that was part of the
dist-upgrade. You should be able to reproduce the error the same way, and
reproduce the fix per the above instructions, see
https://docs.sandstorm.io/en/latest/vagrant-spk/installation/ for how to
install vagrant-spk, and then hopefully you'll be able to get to the bottom
of it from your perspective.

Best of luck!

**Comment by ndarilek** [comment] 2016-02-18 15:56
So if I change `apt-get dist-upgrade -y` to `apt-get upgrade -y`, I still have to halt/re-up. But that does appear to get past the error. Maybe something is happening with vagrant-vbguest upgrading the kernel and modules to account for the fact that the box ships with 4.3's guest support and I'm running 5.0?

**Comment by paulproteus** [comment] 2016-02-18 16:08
It's possible that vagrant-vbguest is involved, although I personally don't
use vagrant-vbguest anymore. I would suggest disabling it and seeing if the
problem goes away (although I do understand that disabling it could make
the problem worse).

**Comment by ndarilek** [comment] 2016-02-18 16:11
I can try, though I'm not sure that will work since my guest support 
will differ by an entire major version.

At the moment I'm attempting to get a Loomio demo up and running that I 
can make available to appdemo, so I'll try the build without vbguest in 
a day or 2 and report back.

**Comment by paulproteus** [comment] 2016-02-18 16:16
+1, the perfect can be the enemy of the good

**Comment by samuk** [comment] 2016-04-28 08:53
@ndarilek Did you make any progress on this one? Or are you stuck?

**Comment by paulproteus** [comment] 2016-05-02 21:50
Hi @ndarilek 

Since you're able to get past the crash, by changing `dist-upgrade` to `upgrade`, I'm going to close this for now. Let me know if you think I should do something different.

**Closed by paulproteus** 2016-05-02 21:50 UTC
