### ISSUE TITLE
Rocket chat is out of date

### ISSUE THREAD

**Issue by jwentwistle** [sandstorm-io/sandstorm#1870] opened 2016-04-18 23:42 UTC
I can't use the android application to connect to the sandstorm server. It says it the version needs to be updated.

**Comment by zarvox** [comment] 2016-04-18 23:49
Rocket.Chat's mobile clients still don't work with Sandstorm; see https://github.com/RocketChat/Rocket.Chat/issues/1352

Duplicate of #1636; so I'm closing this one.

**Closed by zarvox** 2016-04-18 23:49 UTC
