### ISSUE TITLE
Latest update (https://dl.sandstorm.io/sandstorm-228.tar.xz) - Seems to have broken base URL handling

### ISSUE THREAD

**Issue by timshannon** [sandstorm-io/sandstorm#3051] opened 2018-03-05 15:36 UTC
You can see what I'm currently seeing on my sandstorm instance at https://sand.townsourced.com

This appears to have started happening after an update that got installed on March 5th, 2018.  
```
root@sand:/opt/sandstorm# tail /opt/sandstorm/var/log/updater.log
** Successfully updated; restarting.
** Time: Sun Mar  4 09:35:09 2018
Checking for updates on channel dev...
No update available.
** Time: Mon Mar  5 08:58:50 2018
Checking for updates on channel dev...
Downloading: https://dl.sandstorm.io/sandstorm-228.tar.xz
Checking signature...
Signature is valid.
** Successfully updated; restarting.
```

I'm not aware of any other changes to this server or to the domain, and I've confirmed that both the sand.townsourced.com domain and the *.townsourced.com domain are setup properly and pointing at the same IP.

Here's my sandstorm.conf file:
```
root@sand:/opt/sandstorm# cat /opt/sandstorm/sandstorm.conf
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=https://sand.townsourced.com
WILDCARD_HOST=*.townsourced.com
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=25
```
Note, I'm running on port 6080 and directing traffic to it via nginx.  The only change I can see that happened is the sandstorm update.

```
root@sand:/opt/sandstorm# dig -t TXT sandstorm-www.sand.townsourced.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> -t TXT sandstorm-www.sand.townsourced.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 47094
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;sandstorm-www.sand.townsourced.com. IN TXT

;; AUTHORITY SECTION:
townsourced.com.        80541   IN      SOA     ns1.linode.com. tim.townsourced.com. 2017120840 14400 14400 1209600 86400

;; Query time: 0 msec
;; SERVER: 198.58.111.5#53(198.58.111.5)
;; WHEN: Mon Mar 05 09:42:39 CST 2018
;; MSG SIZE  rcvd: 114
```

Let me know if I can get you any additional information.

Thanks,

**Comment by timshannon** [comment] 2018-03-05 18:56
Looks like I'm missing some TXT domain entries that are required by web publishing (https://docs.sandstorm.io/en/latest/developing/web-publishing/), however I currently am not publishing anything.  It appears this is now a requirement on startup?  If so what `publicId` do I use if I don't have any apps that use it?

**Comment by ocdtrekkie** [comment] 2018-03-05 18:58
You shouldn't be getting a sandstorm-www thing for the base domain, that's specifically for things like static published grains that would generally be on subdomains of your Sandstorm instance.

**Comment by ocdtrekkie** [comment] 2018-03-05 18:59
I don't know the details of what @kentonv changed in this release, so I don't know if this is a configuration issue that can be fixed on your end, or a bug that needs to be fixed on his.

**Comment by kentonv** [comment] 2018-03-05 19:19
@timshannon This is strange -- Sandstorm is acting like you requested some hostname other than the one defined by BASE_URL.

Are you running Sandstorm behind an nginx or similar reverse proxy? What is the proxy config? Is it possible that it is not forwarding the Host header correctly?

Another thing to check for: Is it possible that your sandstorm.conf's BASE_URL setting has extra invisible characters in it? Maybe it has a DOS line ending, for example? Can you attach the raw file so I can look at it?

**Comment by timshannon** [comment] 2018-03-05 19:38
Yep, I'm behind an nginx proxy.  The proxy config, and the sandstorm.conf file are attached.

[sandstorm_conf.zip](https://github.com/sandstorm-io/sandstorm/files/1782307/sandstorm_conf.zip)

Neither of which has changed, although that doesn't necessarily mean there isn't something incorrect in there.

**Comment by kentonv** [comment] 2018-03-05 20:14
I've stared at these configs and the code for a while and I can't see how this failure could be happening. Somehow the condition `host == baseUrl.host` on this line is evaluating false:

https://github.com/sandstorm-io/sandstorm/blob/master/src/sandstorm/gateway.c++#L338

But both `host` and `baseUrl.host` are used in the construction of the error page, where they are clearly identical.

@timshannon Have you tried restarting Sandstorm / rebooting the machine?

**Comment by timshannon** [comment] 2018-03-05 20:24
@kentonv yep, I've restarted sandstorm, nginx, and the entire box.

I've also tried adding a blank TXT entry in my dns config for sandstorm-www.sand.townsourced.com, but that didn't seem to work either.

When I try to forward the 6080 port over ssh I can't connect to anything listening on 6080:
`ssh -L 6080:localhost:6080 sand.townsourced.com`

Is that normal? If the sandstorm.conf file has 6080 as the port, shouldn't something be listening there?

**Comment by kentonv** [comment] 2018-03-05 20:36
@timshannon Don't add a TXT record, that's only relevant for static publishing hosts, not for the main host.

Sandstorm is clearly accepting connections from nginx so I don't know why the port forwarding isn't working for you, but that's probably unrelated.

Would you be willing to temporarily give me an SSH account on the box to poke at it? Here's my SSH public key:

    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmPFJ2hhbt6WY4U6HRPLc/CAF/g7mDQOSgfQ+yo9UFee2KrPCjtzbT/vpgCGtKGh+2stNmiBByQY/Z20i5U2oEuHKmyoNCI6ktsq7pYTekgqq9PFV8tG6vxEcD6wxbnLy/raMOr+hoHb0K+tmTpa3HDrzL8iuXMMD7nf8KqGkT39vu2qCo+8BSbYpw68+L5tjbAr5xFKw3nUL9jklGe69f2ZpGb73QxIlEJuyhLQWyHi85dCw+YFNAYdqTOR0jAbJ9jX1cgHKsS/LP/W1zJn1iynCBjIyTXk1nIe0eiapTUYTXGr8YbUzH0FKP4llCnxvEa1Yrk9mzBkwJV+wAEq5L kenton

**Comment by timshannon** [comment] 2018-03-05 20:52
@kentonv done.

Give it a try and let me know if you can't log in, although if other people aren't having issues with this, it's probably an issue with my environment.  No need to spend a ton of time troubleshooting this for me.

My next step would be to setup another VM and try to replicate this in a fresh environment.

**Comment by kentonv** [comment] 2018-03-05 21:21
Oh, I see what the problem is. Your BASE_URL is *inside* your WILDCARD_HOST.

    BASE_URL=https://sand.townsourced.com
    WILDCARD_HOST=*.townsourced.com

Apparently, the old code would compare with BASE_URL first, then WILDCARD_HOST after that. The new code matches against WILDCARD_HOST first, and only when that fails does it check BASE_URL. So, Sandstorm is seeing `sand.townsourced.com` and it thinks this is a request for the wildcard ID `sand`, which it then fails to map to any grain.

An immediate fix would be to change your WILDCARD_HOST like:

    WILDCARD_HOST=ss-*.townsourced.com

By adding the ss- prefix, you avoid the overlap with the BASE_URL.

However, this changes how some URLs are generated which might break some things you have set up:

* If you have any web sites hosted by e.g. WordPress and you were using them at their default URL, which looks like `<long-hex-string>.townsourced.com`, those URLs won't work anymore.
* If you have any API clients, like git clients or the TTRSS mobile app, configured to talk to grains on your Sandstorm server, they won't be able to get through.

You can either re-configure those things to use the new URLs, or you can leave them broken until I have a chance to fix the bug, then switch your config back.

**Comment by kentonv** [comment] 2018-03-05 21:21
(I will try to push a new release tonight to fix the underlying problem.)

**Comment by timshannon** [comment] 2018-03-05 21:23
Makes sense.  Thanks for digging into this.

**Closed** 2018-03-06 05:05 UTC

**Comment by r0h17** [comment] 2018-06-07 00:04
@kentonv I am facing with the same issue again. I have a similar settings as @timshannon have. The sandstorm version i am using is 234. Is updating the wildcard not to match the base url the solution for this?
