### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by berndblume** [sandstorm-io/sandstorm#1966] opened 2016-05-11 18:12 UTC
I have installed sandstorm on a home server. I'm using nginx as a reverse proxy.
When creating a paperwork notebook or a Wekan board, I get a white screen, see attached image.
Interestingly, I do *not* get that error when working with Laverna!
In the past, I had problems with WebSocket forwarding in my nginx config. I checked that and it seems OK.
In the log, I'm flooded with these messages:
```
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
```

![image](https://cloud.githubusercontent.com/assets/1131879/15191329/1b7d49ce-1769-11e6-83f2-330e9e7293e9.png)

**Comment by paulproteus** [comment] 2016-05-11 22:33
Hi Bernie,

I'm sort of stumped. Does the JS console log in your browser show anything
interesting?

Is it a matter of the server running out of RAM? If you run "dmesg", do you
see anything related to out of memory?

**Comment by berndblume** [comment] 2016-05-12 04:14
Hi Asheesh,

thanks for the tips!

The instance I tried first had 2.5GB of RAM and 2 CPUs. Now I created a new instance with 8GB of RAM and 4 vCPUs - I think that should suffice…

Unfortunately, still the same effect.

Here’s what I found in my browser console:

05eea1f….js?meteor_js_resource=true:191 openSession error n(anonymous function) @ 05eea1f….js?meteor_js_resource=true:191

Refused to frame 'http://4c61444a0da1f32408a79de8f6e9f011.sand.hau.to/b/sandstorm/libreboard' because it violates the following Content Security Policy directive: "frame-src 'self' http://*.sand.hau.to:6080".

**Comment by paulproteus** [comment] 2016-05-12 18:41
Got it. Can you share your sandstorm.conf? My guess is a port number
disagreement between WILDCARD_HOST and BASE_URL.​

**Comment by berndblume** [comment] 2016-05-12 22:03
Here's my sandstorm.conf:
```
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://sand.hau.to:6080
WILDCARD_HOST=*.sand.hau.to:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
```
Again, everything works fine with Laverna. Wekan and paperwork do not work.

**Comment by paulproteus** [comment] 2016-05-12 22:28
Oh, you have an nginx in front of it, right, that makes it available on
port 80 by doing a reverse proxy?

If so, please do the following things.

1. Adjust BIND_IP to 127.0.0.1, restart Sandstorm, and make sure nothing
new breaks.

2. Adjust BASE_URL to remove the :6080 and WILDCARD_HOST to remove the
:6080  You don't need the :6080 because of your reverse proxy. Restart
Sandstorm, make sure nothing new breaks.

I think that should address the issue. Let me know how that works for you.

**Comment by berndblume** [comment] 2016-05-12 22:53
I am running everything on port 6080: The user types :6080 into the browser, my home roter forwards port 6080 to my nginx, retaining port 6080. Ngnix listens on 6080 and forwards to upstream sandstorm, also port 6080.
What I did after your response is I changed nginx to listen to port 80. Changed my home router port forwarding to map incoming 6080 to port 80 on my nginx. Also changed BIND_IP to 127.0.0.1.
Effect: Everything still the same.
Frankly, I have difficulties understanding how the problem can lie the port setup. If anything was wrong there, how could I use the complete sandstorm GUI, install apps, even use Laverna completely?
To test it, I removed the :6080 from BASE_URL and WILDCARD_HOST. Effect (as expected): nginx error 502, bad gateway.
Thanks, Bernie

**Comment by paulproteus** [comment] 2016-05-12 22:58
Oh - I didn't realize nginx was listening on port 6080! In my manual
testing of your server, it seemed that nginx was listening on port 80. I
too was confused by the possibility that you can use Laverna properly but
not Paperwork.

When I last thought of it, I was only thinking it would be a Sandstorm bug
or weird configuration. Now I wonder if this is a bug in the apps. It looks
like they might be ignoring the port number. I'll investigate that next,
and if so, file a bug against the apps. Thanks for your patience!

**Comment by berndblume** [comment] 2016-05-12 23:19
Oh, that might be!!!
That means for me: I'll have to make sandstorm publicly available on port 80. This will be a challenge for me because me home router forwards port 80 to a different host... And I cannot make port forwarding dependent on the domain name in the router, just dependent on port numbers.
So for now I must probably use two nginx instances after each other (from router to nginx1, from nginx1 to nginx2, from nginx2 to node/sandstorm), kind of a double reverse proxy. I hope that won't induce any problems. I'll let you know how it goes...

**Comment by paulproteus** [comment] 2016-05-12 23:22
That could work! But why involve nginx2 at all? Why not have nginx1 go
straight to node/sandstorm?​

**Comment by berndblume** [comment] 2016-05-12 23:41
Because my router forwards (and needs to continue to forward) port 80 to a production server, running a number of non-sandstorm apps. And the purpose of the whole exercise to test sandstorm on a *different* piece of hardware (an antsle, see https://antsle.com).

**Comment by paulproteus** [comment] 2016-05-12 23:47
(Antsle looks cool!)

Thanks for explaining; I think I understand better. For what it's worth, a
common configuration is to use nginx to look at the "Host" header, and
based on that, pick which internal machine to send the request to.​

https://github.com/sandstorm-io/sandstorm/blob/master/docs/administering/sample-config/nginx-example.conf
is an example config file that does that - notice that it only covers "
 server_name example.com *.example.com;" which for you would be
"server_name sand.hau.to *.sand.hau.to;".

You don't have to go that route, but I wanted to present another option.
This should work OK for you if your router sends port 80 to a machine whose
nginx config you are OK with changing.

I'll test out the two apps that didn't work now, and see if I can reproduce
your problems. From what I read, they were:

- Paperwork, and

- Wekan

**Comment by paulproteus** [comment] 2016-05-12 23:52
I adjusted my own server to use port 6080 and I can use Paperwork OK. Example sharing link:

- http://asheeshdev.sandcats.io:6080/shared/K78OtsU7XcrGddo9xafxZkbkbwuLAQR-0L169cwp4rd

Same with Wekan. Example sharing link:

- http://asheeshdev.sandcats.io:6080/shared/AO7ds7W9DW1mNbi2tjJcivsfP4kEVQAmjNrW3iUaXe0

My server (in this case) doesn't use nginx, just 100% Sandstorm.

I wonder if there is something in your nginx configuration that is rewriting the content or the headers of the requests that isn't working properly. Are you willing to share your nginx config files that affect the port 6080 Sandstorm, so I can check them to make sure they are OK?

If you prefer to do that privately, you can reach me and a tiny number of Sandstorm employees at: support@sandstorm.io

**Comment by berndblume** [comment] 2016-05-12 23:57
Thanks, Asheesh! Yes, I do froward based on domain names in my nginx isntances. The thing is there is no nginx in my router, so I do need these two steps, but that is just for testing and due to me running kind of complete "datacenter" in my home, consisting of three antsle servers, each running ~20 VMs... :-) That won't be the case for any antsle clients, though...
I configured everything and indeed, Wekan does work now!!! :-) Thanks for the great support!
The good news: sandstorm is running inside a libvirt LXC container - so no real VM (KVM-based) is needed! That is really awesome!
Do you have any tips what might be good choice regarding memory? Would 2GB be fine? Or do we need more for sandstorm to run smoothly?
Thanks, Bernie

**Comment by paulproteus** [comment] 2016-05-23 18:23
Hi Bernie! Thanks for writing all this, and I'm glad ​it worked out for you.

2 GB of RAM for Sandstorm should be fine, in our experience.
https://docs.sandstorm.io/en/latest/administering/faq/#what-are-the-minimum-hardware-requirements
discusses hardware requirements in a very minimal way, additionally.

**Comment by zarvox** [comment] 2016-08-10 22:11
It looks like this bug got resolved some time ago, so I'm going to go ahead and close this ticket.

Feel free to file a new ticket if you're having trouble in the future!

**Closed by zarvox** 2016-08-10 22:11 UTC
