### ISSUE TITLE
Show URL of sharable link in "who has access"

### ISSUE THREAD

**Issue by zeigerpuppy** [sandstorm-io/sandstorm#1936] opened 2016-05-02 12:16 UTC
When a sharable link is created, it's possible to copy the URL of the link.

However when one looks at the "see who has access" panel, it is not possible to see the URL from the shared links.

It would be really useful to be able to see the URL of the shared link so that it can be reused.

**Comment by ocdtrekkie** [comment] 2016-05-02 14:04
This is a "feature", not a "bug". Since these links issue permissions, they're being treated as secrets, like passwords. I don't remember where the thread or issue is, but Kenton explained his reasoning for it pretty well.

I actually keep a grain of my public share links I want to reuse to circumvent this.

**Comment by kentonv** [comment] 2016-05-02 17:05
The server actually does not store the secret URL, only a hash. This means the server can verify that a user is visiting the correct URL, but it cannot reproduce the URL on-demand. This is a security feature.

That said, many people have asked for the ability to obtain the "same" URL again. To that end, we plan to add a button which actually generates a _new_ URL but treats it as the same URL for UI purposes, so you still see only one entry in the table which controls both the new and old URLs.

**Comment by zeigerpuppy** [comment] 2016-05-02 23:44
that sounds reasonable, thanks for the explanation.  It may also be interesting to have some stats available on the number of times a link has been accessed.

**Comment by gwillen** [comment] 2016-05-04 23:09
@kentonv With the new button, would the new and old URLs also be revoked together if revocation happens? (Are they treated as a single capability internally, or just at the UI layer?)

**Comment by paulproteus** [comment] 2016-05-04 23:12
Yeah, revoked together is the idea.​

**Comment by ocdtrekkie** [comment] 2020-01-17 18:53
I'm closing this, as the choice not to do this (and make this impossible) is a security feature. Additionally, #2800 covers the wish case of knowing how many times a link has been accessed.

**Closed by ocdtrekkie** 2020-01-17 18:53 UTC
Labels: wontfix
