### ISSUE TITLE
Highlighted box for guided tour (grains) doesn't dismiss itself

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1653] opened 2016-03-15 20:50 UTC
After clicking on "create new board" and having the Wekan UI load, the highlighted box from the guided tour still displayed. User paused for a moment then clicked on "got it" to dismiss it. Seems odd & unexpected for it to not go away after clicking on "create new board."

The guided tour should disappear after the user has taken the action it suggested to take, in this case "create new board."

(I spotted this while watching our most recent user test video. The cool thing about having screenshots of the demo is that it displays the timer too!)

![image](https://cloud.githubusercontent.com/assets/855341/13793426/15036f24-eab4-11e5-8e26-22d78445ae52.png)

![image](https://cloud.githubusercontent.com/assets/855341/13793197/fd8a62c2-eab2-11e5-826f-186cb2370a98.png)

![image](https://cloud.githubusercontent.com/assets/855341/13793529/83658560-eab4-11e5-9cae-c226c72068cd.png)

**Comment by paulproteus** [comment] 2016-03-15 20:52
Interesting. What browser were you using, and what browser was the test
subject using?

**Comment by neynah** [comment] 2016-03-15 20:56
I just took screenshots of the video, they were using Chrome. Not sure what version but I could ask.

**Comment by paulproteus** [comment] 2016-03-15 20:57
"Chrome" is an OK answer. Interesting. I will dig into this.

**Comment by kentonv** [comment] 2016-03-18 23:43
FWIW this is a dupe of #1573 except that apparently it's not just IE.

**Comment by kentonv** [comment] 2016-03-18 23:44
(#1573 has more details on exactly how to reproduce.)

**Comment by kentonv** [comment] 2016-03-18 23:46
(However, the problem does not repro for me in Chrome on Linux. :( )

**Comment by neynah** [comment] 2016-03-29 06:22
Related issue discovered in latest user test(March 23):

Immediately after clicking "Install", the tour guide begins but the "create new grain" button is not displayed in the highlighted area. User also attempted to click on it(it's faintly visible) in this state and did not succeed.

![image](https://cloud.githubusercontent.com/assets/855341/14099510/f0ea7128-f53a-11e5-9c1d-40a2f7d57ee2.png)

Browser: Firefox 45.0.1

**Closed** 2016-04-01 22:06 UTC
Labels: usability
