### ISSUE TITLE
spk dev fails with Input/output error on Ubuntu 16.04

### ISSUE THREAD

**Issue by mokomull** [sandstorm-io/sandstorm#2526] opened 2016-09-10 05:39 UTC
When running `spk dev` on Ubuntu 16.04, it fails with:

```
$ spk dev
App is now available from Sandstorm server. Ctrl+C to disconnect.
*** Uncaught exception ***
sandstorm/fuse.c++:369: failed: read(/dev/fuse): Input/output error
stack: 0x56ab9b 0x56865c 0x5e240b 0x5e0fdd 0x48b3a0 0x48aeb8
```

This occurs with the official Ubuntu kernel packages (tested with `4.4.0-36-generic`), but does **not** occur with the package of `4.4.14-040414-generic` from http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4.14-xenial/.  This also does not appear to affect any previous versions of Ubuntu.

I tracked this down to an [Ubuntu-specific patch](http://kernel.ubuntu.com/git/ubuntu/ubuntu-xenial.git/commit/?id=9b869708bde3dd34f0e1c59c7c2abe1e433e5b35).  This patch adds a check at time-of-fd-use that the file descriptor for `/dev/fuse` has not crossed a pid namespace boundary; this interferes with the way Sandstorm mounts the root filesystem and sends the file descriptor via a SCM_RIGHTS message to the `spk dev` running as the developer.  I have confirmed that `spk dev` functions correctly after reverting that individual commit (and fixing some conflicts).

**Comment by mokomull** [comment] 2016-09-10 05:48
There was some discussion on IRC about this [around 23rd and 24th of July](https://botbot.me/freenode/sandstorm/2016-07-23/?msg=70133690&page=1), but I don't think a conclusion was reached as to the path forward.

**Comment by dckc** [comment] 2016-11-01 02:07
Is there any workaround for this?

**Comment by mokomull** [comment] 2016-11-01 02:23
The only workaround I know of is to use a [mainline kernel built by the Canonical kernel team](https://wiki.ubuntu.com/Kernel/MainlineBuilds), as I don't see a way around this codepath in the generic kernel.

I'm actually attending Linux Plumbers Conference this week — if I run into someone who knows more about it than I do, I'll update this issue.

**Comment by mrdomino** [comment] 2017-03-12 21:24
This is also happening in 16.10.

**Comment by mnutt** [comment] 2017-03-14 02:30
The original issue I had on 4.4.0 also occurs on 4.8.0-41, unfortunately.

**Comment by urakagi** [comment] 2017-04-11 09:22
This issue still seems to exist. Is downgrading to 15.10 or even 14.04 LTS a better idea?

**Comment by ocdtrekkie** [comment] 2017-08-03 14:41
I've got someone who appears to be getting this error on Ubuntu 14.04.1 with kernel 4.4.0-87-generic.

**Comment by zenhack** [comment] 2017-08-03 16:26
Has anyone tried reporting a bug to Ubuntu? From the commit message:

> Since no use case currently exists for changing namespaces all
> translations are done relative to the pid namespace in use when
> /dev/fuse is opened. Mounting or /dev/fuse IO from another namespace
> will return errors.

Perhaps worth bringing our use case to their attention.

**Comment by ocdtrekkie** [comment] 2017-08-03 16:33
I lack the Linux fu to make a competent report to them. The person I am working with successfully switched to a mainline kernel though and is able to proceed.

**Comment by xet7** [comment] 2017-08-03 20:49
Yes, I did have to [install that kernel to build Wekan spk](https://github.com/wekan/wekan-maintainer/wiki/Building-Wekan-for-Sandstorm) on Ubuntu 14.04.5

**Comment by xet7** [comment] 2017-08-03 21:03
@kubiko

Do you know is there already bug report about this in Ubuntu Launchpad ?

**Comment by kubiko** [comment] 2017-08-04 06:23
@xet7 sorry but not really my domain, if this is something kernel has fixed best to search kernel bugs in launchpad

**Comment by zenhack** [comment] 2017-08-04 23:17
Here's the launchpad bug that patch was intended to fix:

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1605344

**Comment by xet7** [comment] 2017-08-15 19:50
When running kernel 4.4.14 on Ubuntu 14.04 on VirtualBox, VirtualBox extensions do not work, screen stays in low resolution.

This can be fixed by:

1) Installing newer gcc version 4.9

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test

sudo apt-get update

sudo apt-get install gcc-4.9

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
```

2) Reinstalling VirtualBox extensions from VirtualBox Device menu.

[Info source at VirtualBox forums](https://forums.virtualbox.org/viewtopic.php?f=7&t=76032)

[Info source at AskUbuntu](https://askubuntu.com/questions/428198/getting-installing-gcc-g-4-9-on-ubuntu)

I also added info about this to [Wekan Sandstorm spk page](https://github.com/wekan/wekan-maintainer/wiki/Building-Wekan-for-Sandstorm#4-install-gcc-version-that-works-for-compiling-virtualbox-extensions-on-kernel-4414).

**Comment by zenhack** [comment] 2017-09-05 04:22
It looks like that patch has been pushed into the upstream kernel:

https://github.com/torvalds/linux/commit/0b6e9ea041e6c

I'd planned on trying to report the bug to ubuntu, but couldn't sort out the logic with what sandstorm is doing here well enough to feel like I could explain it coherently in a bug report. This being upstreamed makes it a bit more important though.

//cc @kentonv

**Comment by mokomull** [comment] 2017-09-05 21:22
It's been quite a while since I've looked at what `spk dev` does behind-the-scenes, and I completely missed this patch reaching mainline — looks like it was merged into the v4.12 release.

If no one has better connections in the kernel community, I can try to get something written-up for LKML, but the last discussion I see about the relevant patch is [from more than a year ago](1461699396-33000-19-git-send-email-seth.forshee@canonical.com).  We don't seem to be [the only ones](CA+2rt426_pshAauQizcxkfAq16vmEpB4sJ4genW_ucosH3j=zQ@mail.gmail.com) that saw a regression, but it doesn't look like anyone has published a patch for the agreed-upon workaround.

**Comment by zenhack** [comment] 2017-09-06 00:08
@kentonv emailed the folks in the signed-off-by fields on that commit. They've acknowledged the regression, and the fuse maintainer sent us an (untested) patch from one of the developers. Hopefully sometime this week I'll have time to test it myself, but I'm going to attach it to this post in case someone else wants to take a whack at it. (Note that I've added a .txt extension, because github has a whitelist of extensions for some reason).

[fuse-allow-server-to-run-in-different-pid-ns.patch.txt](https://github.com/sandstorm-io/sandstorm/files/1279340/fuse-allow-server-to-run-in-different-pid-ns.patch.txt)

**Comment by zenhack** [comment] 2017-09-06 00:30
The relevant bits of conversation on IRC last night: https://botbot.me/freenode/sandstorm/2017-09-05/?msg=90688526&page=1

**Comment by mokomull** [comment] 2017-09-07 03:44
I got my kernel test machine back up and running, and verified that `spk dev` fails with EIO on stock 4.12, and that this patch applies cleanly and successfully runs `spk dev`.

Tested-by: Matt Mullins <mmullins@mmlx.us>

**Comment by zenhack** [comment] 2017-09-07 04:10
Quoting Matt Mullins (2017-09-06 23:44:40)

>    I got my kernel test machine back up and running, and verified that spk
>    dev fails with EIO on stock 4.12, and that this patch applies cleanly
>    and successfully runs spk dev.

Yep, I've just tested it myself, and can also confirm that it fixes the
problem.

**Comment by zenhack** [comment] 2017-09-14 19:02
This has now been merged into Linus's tree:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5d6d3a301c4e749e04be6fcdcf4cb1ffa8bae524

**Comment by kentonv** [comment] 2017-09-17 01:33
Guess this is fixed, then!

**Closed by kentonv** 2017-09-17 01:33 UTC

**Comment by ocdtrekkie** [comment] 2017-09-22 06:18
Any idea if/when any given Ubuntu version will have this fix?
