### ISSUE TITLE
Privacy and tracking

### ISSUE THREAD

**Issue by zeigerpuppy** [sandstorm-io/sandstorm#1616] opened 2016-02-28 22:55 UTC
I noticed that my sandstorm installation is trying to access scripts from
google-analytics.com and trello.com

My users are very privacy conscious and certainly don't want to be tracked by google,
is there a way to turn off any third party scripts server-side?

**Comment by kentonv** [comment] 2016-02-28 23:55
@zeigerpuppy Can you provide more detail on what you're seeing? Sandstorm itself definitely shouldn't be loading any scripts from third-party domains. It's possible that an app is doing so -- we intend to block these in the future but haven't done so yet. Which apps do you have open when you see these requests? We should file bugs against those apps to get these removed. (Eventually, Sandstorm will directly prohibit such off-site requests, but there are some issues we need to solve first.)

**Comment by kentonv** [comment] 2016-03-05 02:16
I cannot reproduce this. If you can provide more information let me know, but I'm closing for now.

**Closed by kentonv** 2016-03-05 02:16 UTC
