### ISSUE TITLE
installer maybe not recognize CONFIG_USER_NS

### ISSUE THREAD

**Issue by port22** [sandstorm-io/sandstorm#488] opened 2015-06-10 19:48 UTC
Hi,

running on CentOS7 with (a stock) kernel 3.10.0-229.4.2.el7.x86_64
I cant get sandstorm installed because of message:

Your kernel does not appear to be compiled with support for unprivileged user 
namespaces (CONFIG_USER_NS=y), or something else is preventing creation of user 
namespaces.

But the kernel is compiled with:
`# grep "CONFIG_USER_NS" /boot/config-3.10.0-229.4.2.el7.x86_64`
`CONFIG_USER_NS=y`

also, kernel has: CONFIG_NAMESPACES=y

Any suggestions what's the problem?

**Comment by ocdtrekkie** [comment] 2015-06-10 19:49
Your first problem will be that Sandstorm requires 3.13 or later.

**Comment by port22** [comment] 2015-06-10 19:52
Oh, I see - compiling manually is unfortunately not possible. Will it likely work then if I wait until 3.13 is available?

Thanks for your help!

**Comment by ocdtrekkie** [comment] 2015-06-10 19:55
One of the Sandstorm folks would likely be better equipped to comment on the specifics, as I am not much of a Linux user myself. :/ I also want to use a RHEL/CentOS-type setup for Sandstorm at some point, but it does seem that it'll likely that we'll have to wait for RHEL/CentOS 8 before they ship a new enough kernel.

**Comment by ocdtrekkie** [comment] 2015-06-10 19:57
Note that this is still a good "issue" for the Sandstorm folks to look at, because the error message may need to be better. Since clearly it is telling you you need a config option which you do in fact have.

**Comment by ocdtrekkie** [comment] 2015-06-10 19:58
It seems likely #480 was intended to address this, but I don't know if the install script has been, in fact, updated since that PR was merged.

**Comment by paulproteus** [comment] 2015-06-10 20:09
Yeah -- I think the `install.sandstorm.io` site is out-of-date. Let me see what the best way is to get it updated.

@ocdtrekkie thanks for answering this question!

@port22 thanks for raising the issue! And yeah, you'll need Linux 3.13 or newer to use Sandstorm.

**Comment by paulproteus** [comment] 2015-06-10 20:21
@port22 can you retry now, and make sure that it gives you a better error message?

If so, we can close this! Thanks, and apologies for your suffering.

**Comment by port22** [comment] 2015-06-10 20:22
yeah, got a better error message - thanks a lot  XD

**Comment by paulproteus** [comment] 2015-06-10 20:24
Great! Consider using `elrepo`'s newer kernel, per e.g. http://wiki.mikejung.biz/CentOS_7#Upgrade_CentOS_7_Kernel_to_3.17

(Naturally, if that's a bad fit for your needs/environment, don't use it!)

**Closed** 2015-06-10 20:23 UTC
