### ISSUE TITLE
sandstorm broken by update from 0.84 to 0.85

### ISSUE THREAD

**Issue by lunixbochs** [sandstorm-io/sandstorm#463] opened 2015-06-04 18:05 UTC
After the update to 0.85, my sandstorm binary is zero bytes. How should I recover from this without losing data?

**Comment by kentonv** [comment] 2015-06-04 21:58
Yikes.

Was this an auto-update or manual?

To be clear, you're saying that `/opt/sandstorm/latest/sandstorm` is a zero-size file?

Is `/opt/sandstorm/latest` a symlink to `sandstorm-85`?

The binary is unpacked from a tarball. I'm confused how tar could report success but unpack something different from the rest of the world.

If the assumptions above are correct then you should be able to recover by doing the following as root:

    cd /opt/sandstorm
    rm -rf sandstorm-85
    wget https://dl.sandstorm.io/sandstorm-85.tar.xz
    tar Jxof sandstorm-85.tar.xz
    rm sandstorm-85.tar.xz
    sandstorm start

Let me know how it goes.

**Comment by kentonv** [comment] 2015-06-04 21:59
Also you might want to check the end of `/opt/sandstorm/var/log/sandstorm.log` to see if there's any hints about what went wrong.

**Comment by lunixbochs** [comment] 2015-06-04 23:42
Your steps fixed it.

Sandstorm was causing a kernel panic. I ran a manual update command (which updated from 0.84 to 0.85) in an attempt to fix it before I found #461.

After rebooting with a fixed kernel, latest was pointed at sandstorm-85 but `sandstorm-85/sandstorm` was empty. I just checked, and *all* of the files in the 0.85 folder were empty.

I'm guessing something screwed up with flushing disk cache as it kernel panicked immediately after update.

**Comment by kentonv** [comment] 2015-06-04 23:52
Wow, ok, so the problem was actual filesystem corruption caused by kernel panic. Indeed, that makes sense. Sorry about that.

Are you on Fedora or Linode, or is there some other environment that is shipping an unpatched 4.0.4? (Or is it self-built?)

**Comment by lunixbochs** [comment] 2015-06-05 00:05
Linode latest is still on 4.0.4, and they forced a reboot on me recently for some reason.

**Comment by kentonv** [comment] 2015-06-05 00:21
OK, closing as a dup of #461. We've let Linode know about the problem so hopefully they'll fix it soon.

**Comment by dwrensha** [comment] 2015-07-07 14:38
Closing because it looks like @kentonv intended to close this a month ago.

Note that the latest Linode kernels no longer run into this particular panic.

**Closed by dwrensha** 2015-07-07 14:38 UTC
