### ISSUE TITLE
Update available notification needs more information

### ISSUE THREAD

**Issue by jdougan** [sandstorm-io/sandstorm#3438] opened 2020-09-22 02:25 UTC
The update available notifications in sandstorm need to provide more information, at least a link to a web page the describes the update. I would not have had the problems if I had been pointed to an update notice that explained the contents so I could take precautions. This goes both for sandstorm updates and grain app updates. I don't know if there is provision for this already and people just aren't using it, or if it currently isn't supported.

**Comment by ocdtrekkie** [comment] 2020-09-22 02:48
I would contend this is a duplicate of #2280. And we definitely discussed this during the rollout process for the new TTRSS.

**Closed** 2020-09-22 02:50 UTC
Labels: app-platform, enhancement, shell
