### ISSUE TITLE
Migrate Wordpress using files only

### ISSUE THREAD

**Issue by kfriede** [sandstorm-io/sandstorm#345] opened 2015-04-23 00:15 UTC
I am attempting to migrate an existing Wordpress installation. I have a backup of the file directory, as well as the database(s), but cannot find their locations on my sandstorm.io server. How may I transfer this?

**Comment by dwrensha** [comment] 2015-04-23 18:23
Hi!

You'll first need to export the data from the old installation as an XML file with the export tool. Then you can import data with WordPress Importer plugin, which is included with the WordPress app. Sadly, media  import doesn't work yet because it requires the app to make external HTTP requests; I'm waiting until the powerbox is implemented to enable them.

You might be able to import the database and posts through the importer tool and then import any media directly through the filesystem (even though this is not the way Sandstorm was designed to be used). Once you create a WordPress grain, its data is stored in `<SANDSTORM_PATH>/var/sandstorm/grains/<GRAIN_ID>` where `SANDSTORM_PATH` is usually `/opt/sandstorm` and `GRAIN_ID` can be read from the address bar of your browser when you visit the grain: `https://sandstorm.example.com/grain/<GRAIN_ID>`.

If you have further problems with the WordPress port, it may be more appropriate to word them here: https://github.com/dwrensha/wordpress-sandstorm/issues

**Comment by kfriede** [comment] 2015-04-24 21:02
Thanks for the input.  I tried placing the files in the grain root, but decided against migrating the mysql database to sqlite for the long term.  I just installed wordpress separately for the time being.

**Comment by paulproteus** [comment] 2015-04-25 03:20
Thank you for writing about this, Kevin!

I think data portability _into_ Sandstorm is something that's going to be
essential for people to find the project interesting, so it's useful to
hear about what you tried and to think about how we could make that easier.
​

**Comment by ocdtrekkie** [comment] 2020-02-03 21:53
I am going to go ahead and close this, as it's a WordPress issue, not a Sandstorm issue, and we also have a significantly newer WordPress release than when this issue was filed. Sandstorm's WordPress depends on SQLite as the database backend, so migrating while staying on MySQL isn't going to work unless you create your own package.

As an aside/update before closing this, the current repo for WordPress on Sandstorm issues is https://github.com/sandstormports/wordpress-sandstorm

**Closed by ocdtrekkie** 2020-02-03 21:53 UTC
