### ISSUE TITLE
Usability issue: left side bar seems to be impossible to hide

### ISSUE THREAD

**Issue by shamrin** [sandstorm-io/sandstorm#1104] opened 2015-10-31 11:02 UTC
## The problem

I've been playing with Sandstorm for quite a while and was mildly annoyed about the left side bar (sandstorm chrome) wasting my screen space. I thought: "it would nice if I could hide it". But it seemed to me it's possible to hide, so I moved on.

But some day I clicked top left button (I don't know why I did it, but I thought it would bring me to sandstorm.io front page). And then - wow! - it collapsed the side bar! Only then I noticed the logo has a small triangle. I thought the triangle is just part of the logo, not a separate indicator.

![backgroundtest sandstorm 2015-10-31 13-22-51 2015-10-31 13-24-42](https://cloud.githubusercontent.com/assets/510678/10863093/4f4b422a-7fd3-11e5-971d-51f7aa6d0681.jpg)

I would argue it's confusing to new users.

## Possible solution

YouTube puts separate hamburger menu to the left of the logo:

![open web apps without the pain with sandstorm io feat jack singleton - youtube 2015-10-31 13-42-56 2015-10-31 13-43-01](https://cloud.githubusercontent.com/assets/510678/10863170/5c9206e2-7fd5-11e5-92af-f4375f317b5d.jpg)

Hamburger menu is probably not the best idea usability wise. Lot's of people argue against it ([1][1], [2][2], [3][3]), but it's still better than the impossible-to-see triangle.

[1]: http://deep.design/the-hamburger-menu/xz
[2]: http://blog.manbolo.com/2014/06/30/apple-on-hamburger-menus
[3]: https://lmjabreu.com/post/why-and-how-to-avoid-hamburger-menus/

**Comment by neynah** [comment] 2015-11-02 18:43
Hi @shamrin I agree that that arrow is not intuitive. We've also confirmed this with usability testing and I've proposed a new design. See #872 and let me know if this is better. :)

The hamburger menu could also be an option but our mobile UI currently uses this and has different menu options so we've decided to avoid that confusion for now.

**Comment by paulproteus** [comment] 2016-01-12 23:22
Closing due to the redesign of the sidebar with a little left-right arrow!

**Closed by paulproteus** 2016-01-12 23:22 UTC
