### ISSUE TITLE
No sign-in button on shared-link page

### ISSUE THREAD

**Issue by Spirotot** [sandstorm-io/sandstorm#902] opened 2015-09-19 10:26 UTC
![sandstorm_no_signin](https://cloud.githubusercontent.com/assets/737657/9975789/3b16dd44-5e97-11e5-8d80-804c7b9bbcc4.png)

^--- That's a Let's Chat grain. Didn't there used to be a sign-in button in the upper-right corner? If not, there could/should be... :)

**Comment by dwrensha** [comment] 2015-09-19 12:45
This looks like it might be due to #598. Did you happen to resize that browser window? Does it work if you open the link in a new window?

**Comment by Spirotot** [comment] 2015-09-19 12:47
I did resize it, multiple times (including full-screen). And that link was opened in a new windows. The same thing occurred on my friend's computer, too -- he was actually the one who ran into this problem first (we're trying to use apps my Sandstorm server to collaborate on some stuff).

**Comment by zarvox** [comment] 2015-09-21 17:24
All right, closing as a dupe of #598.

On the bright side, the related chromium bug appears to have a patch merged now, so we just have to wait for the update to trickle down: https://code.google.com/p/chromium/issues/detail?id=411256

**Closed by zarvox** 2015-09-21 17:24 UTC
