### ISSUE TITLE
sandstorm translations (i18n)

### ISSUE THREAD

**Issue by mrflos** [sandstorm-io/sandstorm#557] opened 2015-07-03 11:39 UTC
I would like to contribute to this project by allowing to change the language of the sandstorm admin bar. Any plans or guidelines for doing it?

**Comment by kentonv** [comment] 2015-07-03 22:07
Hi Florian,

This is something we definitely want to do, but it might make sense to hold off at the moment as we're in the process of revamping the entire UI, and any translations done now might then just have to be re-done. We should make sure as we code the new UI that we set things up to make translation easy...

**Comment by mrflos** [comment] 2015-07-07 11:04
@kentonv ok thank you, i will follow the future changes, and propose something when the time comes! Happy coding!

**Comment by MaDDmin** [comment] 2017-02-04 18:44
Has this progressed at all?

**Comment by MatheusRV** [comment] 2017-03-12 05:30
Weblate - continuous translation is a nice app to keep the translates update..

**Comment by urakagi** [comment] 2017-08-14 02:35
Is there some suggestion of entry point about how to localize Sandstorm?

**Comment by zenhack** [comment] 2017-08-14 03:04
There's a blurb here:

https://github.com/sandstorm-io/sandstorm/blob/master/CONTRIBUTING.md#internationalization-i18n

@kentonv, suggest re-opening this?

**Comment by urakagi** [comment] 2017-08-14 03:20
Yap I have found that, but I think I need a mentor teach me about how to change HTML templates since I'm new to Meteor. I even don't know where to find the template files :cry:

**Comment by zenhack** [comment] 2017-08-14 23:13
Re: getting started with meteor, I'm sympathetic -- we could really use
a few more active people who knew their way around the framework -- but
unfortunately, I'm not that, and am not really in a position to do
mentoring on the topic of meteor (the size of which has somewhat
discouraged me from trying to hack on sandstorm core myself...). All I
can suggest is going through the tutorial on meteor.com (the one with
blaze, as that's what sandstorm uses).

As to the locations of the templates:

    $ grep -r '<template' shell | sed 's/:.*//' | uniq
    shell/client/notifications.html
    shell/client/setup-wizard/wizard.html
    shell/client/widgets/widgets.html
    shell/client/billing/billingPromptLocal.html
    shell/client/admin/network-capabilities.html
    shell/client/admin/personalization.html
    shell/client/admin/maintenance-message.html
    shell/client/admin/stats.html
    shell/client/admin/app-sources.html
    shell/client/admin/user-invite.html
    shell/client/admin/hosting-management.html
    shell/client/admin/user-details.html
    shell/client/admin/system-status.html
    shell/client/admin/email-config.html
    shell/client/admin/user-accounts.html
    shell/client/admin/identity-providers.html
    shell/client/admin/organization.html
    shell/client/admin/networking.html
    shell/client/admin/admin.html
    shell/client/admin/preinstalled-apps.html
    shell/client/grain/grainlist.html
    shell/client/grain/contact-autocomplete.html
    shell/client/desktop-notifications.html
    shell/client/shell.html
    shell/client/powerbox-builtins.html
    shell/client/apps/install.html
    shell/client/apps/applist.html
    shell/client/apps/app-details.html
    shell/client/styleguide.html
    shell/client/grain.html
    shell/client/accounts/email-token/token-templates.html
    shell/client/accounts/identity/identity.html
    shell/client/accounts/login-buttons.html
    shell/client/accounts/account-settings.html
    shell/client/shell-client.js
    shell/packages/sandstorm-ui-powerbox/powerbox.html
    shell/packages/sandstorm-ui-topbar/topbar.html

(The meteor app is all under `shell/`).

**Comment by caasi** [comment] 2017-08-15 03:42
@urakagi 

I try to setup the i18n environment with tap-i18n and invite you as a collaborator: https://github.com/caasi/sandstorm/commit/3aedb5ac8a0bd879e8273183b167a35b4bfb2593

If you have a local sandstorm installed, you have to change `UPDATE_CHANNEL` in `/opt/sandstorm/sandstorm.conf` to `none`.

Then you can test translations with:

```
make shell-build
make update
```

Should we work together?

**Comment by urakagi** [comment] 2017-08-16 06:51
@caasi 
Of course, I'm reading Meteor documents now, and then will try translations with your fork.
Thanks!

**Comment by caasi** [comment] 2017-08-16 10:46
BTW, I am replacing strings with tap-i18n helpers. You can help me editing `en.i18n.json` or start writing `zh-TW.i18n.json`.

**Comment by mrflos** [comment] 2017-08-16 10:54
Hello, thanks for starting this work!
I could do `fr.i18n.json` and `ru-RU.i18n.json` for french and russian translations.

@caasi : could you tell me when `en.i18n.json` is including all the templates ?
Thanks in advance!

**Comment by caasi** [comment] 2017-08-16 12:53
@mrflos Ok. I will notify you when `en.i18n.json` is ready. It will take many days.

**Comment by urakagi** [comment] 2017-08-16 12:55
OK, I think I'll start with zh-TW.i18n.json tomorrow. If able I'll also add Japanese and maybe simplified Chinese or Vietnamese.

**Comment by ocdtrekkie** [comment] 2017-08-16 13:38
Awesome to see people working on this. 👍 

Probably my biggest question for translators will be how Sandstorm-specific terminology gets translated, and whether or not we'll also need translation of at least some of the basic documentation on what that terminology is. "Grain" is probably the most critical to get right.

**Comment by urakagi** [comment] 2017-08-16 13:39
Grain is very...hard to translate to Chinese. (Japanese will be easy though)
I think I will use a word with similar meaning on Sandstorm, but not similar to the original definition of "grain".

**Comment by urakagi** [comment] 2017-08-17 02:40
@caasi Hello, how are you doing when want to refresh the translation list? I tried "Hakcing on the Shell" in https://docs.sandstorm.io/en/latest/install/, but fails in some root or not root, I don't understand why but Sandstorm tells me to run as root and Meteor tells me you can't run as root and...
Do I need to `make` and `make install` each time I want to check my translations?
Thank you very much.

**Comment by urakagi** [comment] 2017-08-17 03:53
@zenhack Do you know what is Sandstorm's "Startup file" so I can put the language-selecting code into it?
Here is the language-selecting code: https://github.com/TAPevents/tap-i18n#quickstart, Step 4

**Comment by zenhack** [comment] 2017-08-17 06:42
I think the call to Meteor.startup in `shell/client/shell-client.js`
is probably the right spot.

Quoting 蔡仲明 (Romulus Urakagi Tsai) (2017-08-16 23:53:51)

**Comment by caasi** [comment] 2017-08-17 11:53
@urakagi:

I `make shell-build; make upgrade` every time as a normal user with the sudo permission(`ubuntu` in this case).

Any suggestions to speed up this process?

**Comment by urakagi** [comment] 2017-08-18 01:07
@caasi

I have not tried `shell-build; make upgrade`, but by https://docs.sandstorm.io/en/latest/install/, section `Hakcing on the Shell`, I have this console: ![hacking on the shell](http://my.jetscreenshot.com/18082/20170818-yjjr-91kb.jpg)
Then, when any change occurs under `shell/` directory, the front-end will reload automatically.

**Comment by urakagi** [comment] 2017-08-18 05:07
@caasi , I made a small language sync tool for new keys, and it will sort json by keys. Is it troublesome to you?

**Comment by caasi** [comment] 2017-08-18 08:35
Yes. Please do not reorder keys before I finish `en.i18n.json`.

I keep the key order to match the structure of html templates.

**Comment by urakagi** [comment] 2017-08-18 10:25
Okay I have modified the sync tool to keep json order. Please check if your en-i18n.json has correct now. (It's output of the sync tool)

**Comment by caasi** [comment] 2017-08-18 14:01
Yes. Thank you. Now I can rebase my commit. 👍 

BTW, can you remove trailing spaces next time?

**Comment by urakagi** [comment] 2017-08-21 01:28
Okay, I have removed it.

**Comment by caasi** [comment] 2017-08-22 06:38
thanks @kentonv for the list

`en.i18n.json` status:

* [ ] shell/client/
  * [x] notifications.html
  * [x] desktop-notifications.html
  * [x] shell.html
  * [x] powerbox-builtins.html
  * [x] styleguide.html
  * [x] grain.html
  * [ ] shell-client.js
  * [ ] setup-wizard/wizard.html
  * [ ] widgets/widgets.html
  * [ ] billing/billingPromptLocal.html
  * [ ] admin/
    * [ ] network-capabilities.html
    * [ ] personalization.html
    * [ ] maintenance-message.html
    * [ ] stats.html
    * [ ] app-sources.html
    * [ ] user-invite.html
    * [ ] hosting-management.html
    * [ ] user-details.html
    * [ ] system-status.html
    * [ ] email-config.html
    * [ ] user-accounts.html
    * [ ] identity-providers.html
    * [ ] organization.html
    * [ ] networking.html
    * [ ] admin.html
    * [ ] preinstalled-apps.html
  * [ ] grain/
    * [ ] grainlist.html
    * [ ] contact-autocomplete.html
  * [ ] apps/
    * [ ] install.html
    * [ ] applist.html
    * [ ] app-details.html
  * [ ] accounts/
    * [ ] email-token/token-templates.html
    * [ ] identity/identity.html
    * [ ] login-buttons.html
    * [ ] account-settings.html
* [ ] shell/packages/
  * [ ] sandstorm-ui-powerbox/powerbox.html
  * [ ] sandstorm-ui-topbar/topbar.html

**Comment by kentonv** [comment] 2017-08-26 23:10
Hi all,

I'm very excited to see this happening! The approach taken in @caasi's fork looks good to me. Please keep us updated on progress!

**Comment by kentonv** [comment] 2017-08-26 23:13
By the way, note that the identity refactor branch is likely to be merged in about a week:

https://github.com/sandstorm-io/sandstorm/pull/2960

This is a huge change to Sandstorm's code. Not a lot of words have changed in the UI, but some templates have been refactored, so this might be a disruptive merge. I think it should be safe if you want to merge/rebase that branch now and work on top of it, even though it's not in master yet.

**Comment by MatheusRV** [comment] 2017-08-27 01:35
Could I start translating to pt-br? At this moment in sandstorm app store haven't any software to hold translations. Can some one port Weblate or Zanata into ss?

**Comment by malsony** [comment] 2017-08-27 16:04
@urakagi 
Glad to know that I am not the only one translating it into Chinese! I will joint you to work on the Simplified Chinese version, soon.

For now I have tentatively translated Sandstorm to 「沙塔」because of 「聚沙成塔」, Grain 「沙粒」or「顆粒」,  and some more in my own fork for the sandstorm.io website, check it out if you're interested.

**Comment by urakagi** [comment] 2017-08-28 01:04
@malsony 
Hello :smile: 
Sandstorm has been translated into 「沙聚雲」 Taiwanese Government officially in some announcements, since it's a "cloud" service. (I don't know why it's not 聚沙雲, but well it already happened)

**Comment by urakagi** [comment] 2017-08-28 03:49
@caasi 

Do you have idea about how to i18n this string in JS file?
https://github.com/caasi/sandstorm/blob/fddb08a1b2f809e14a392ee5a0daac8ce0155234/shell/client/grain/grainlist-client.js#L253

**Comment by malsony** [comment] 2017-08-28 05:18
@urakagi 
OK, I'll follow the branch of @caasi to use his i18n table.
And what should we do in case there is any new special terms?

**Comment by ocdtrekkie** [comment] 2017-08-28 05:33
Might make sense to do what Wekan does and setting up something like Transifex once this is merged in, so people can work on translations for all of the different strings in different languages, and then Kenton can just push one button to merge the updates in.

**Comment by urakagi** [comment] 2017-08-28 07:19
@malsony I think there's none, but you can check zh-TW.i18n.json here: https://github.com/caasi/sandstorm/blob/master/shell/i18n/zh-TW.i18n.json

**Comment by caasi** [comment] 2017-08-28 11:16
@kentonv Looks like I need to check every changes again after #2960. I will do it after we complete the English language file.

@malsony I will give you the commit bit. ^^

**Comment by caasi** [comment] 2017-08-28 11:20
@urakagi I think we can translate strings in JS files by using `TAPi18n.__` function. check [TAPi18n API](https://github.com/TAPevents/tap-i18n#tapi18n-api) for more information.

**Comment by urakagi** [comment] 2017-09-15 03:05
@caasi @kentonv 
It seems like most of template files are replaced. Do we have a merge plan?

**Comment by caasi** [comment] 2017-09-15 09:19
I think there are some files need to be done:

* [ ] shell/client/
  * [ ] setup-wizard/wizard.html
  * [ ] widgets/widgets.html
  * [ ] billing/billingPromptLocal.html
* [ ] shell/packages/
  * [ ] sandstorm-ui-powerbox/powerbox.html

I'm working on the wizard page.

After we finish those pages, someone should rebase to the upstream. Expecting a lot of conflict.

**Comment by urakagi** [comment] 2017-09-18 08:31
@caasi 
I have replaced powerbox.html, and it seems like widgets.html and billing...html has nothing to replace.
Is wizard page also done?

**Comment by caasi** [comment] 2017-09-21 05:23
@urakagi I'll finish the wizard page tonight.

**Comment by urakagi** [comment] 2017-09-25 01:06
I'm merging and fixing modified templates (13), this will take several days.

**Comment by urakagi** [comment] 2017-09-25 07:32
@caasi @kentonv 
I have done merging, please check if I made something wrong.
If there's no problem we may make a pull request.

**Comment by caasi** [comment] 2017-09-27 08:09
@urakagi 

Thanks for your hard work.

I am ok with it. I think we can patch missing translations in js files later. So you guys in PDIS can have the Chinese version ASAP.

Would you like to initialize the pull request?

**Comment by urakagi** [comment] 2017-09-27 09:07
@caasi 
Okay, I have made a pull request #2985.
This is my first PR, please remind me if I'm doing anything wrong. Thank everyone very much.

**Comment by kentonv** [comment] 2017-10-01 23:36
Hey all,

I'm pretty excited about this! Of course, it's a rather huge change so I'll have to spend some time reviewing. I only work on Sandstorm on weekends, so this might take a few weeks. But I really want to get this in so I'll do my best.

**Comment by urakagi** [comment] 2017-10-23 01:45
Update confirmed, thank you @kenton @cassi and everyone!

**Comment by urakagi** [comment] 2017-10-25 03:39
Anyone close this issue or?

**Comment by MatheusRV** [comment] 2017-11-12 03:30
Now is able to translate? Where i find files to translate to pt-BR.

**Comment by ocdtrekkie** [comment] 2017-11-12 04:09
@MatheusRV Hey, someone on the dev list just popped up about doing pt-BR. Perhaps the two of you can chat? https://groups.google.com/forum/#!topic/sandstorm-dev/ANhSo9RnlxA

The files to look at are here: https://github.com/sandstorm-io/sandstorm/tree/master/shell/i18n

Take a copy of the en-US version, rename it, and edit.

**Comment by kentonv** [comment] 2017-11-13 00:11
Ah yeah, I guess we can close this issue. There are still missing pieces, but we should open new issues for those as needed.

See here for how to contribute translations: https://github.com/sandstorm-io/sandstorm/blob/master/CONTRIBUTING.md#internationalization-i18n

**Closed** 2017-11-13 11:45 UTC
Labels: shell, usability

**Comment by jiuneypachevitch** [comment] 2017-11-13 11:51
@MatheusRV Opa, podemos trabalhar juntos nessa tradução?
