### ISSUE TITLE
Reviews or Comments with lines cut-off

### ISSUE THREAD

**Issue by paragjoshi** [sandstorm-io/sandstorm#2223] opened 2016-07-15 16:13 UTC
Check reviews for draw.io. You can see that several of the longer reviews or app feedbacks have lines cut off and there is no way to click to open full review. This is a clear usability issue.

**Comment by dwrensha** [comment] 2016-07-15 16:45
Closing as duplicate of https://github.com/sandstorm-io/sandstorm-app-market/issues/4.

**Closed by dwrensha** 2016-07-15 16:45 UTC
