### ISSUE TITLE
Page title does not reset when a grain is closed

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/sandstorm#903] opened 2015-09-20 01:44 UTC
If I navigate to a grain, then click its Close button or navigate home, the page title remains the same as the grain's title. I'd expect it to reset to "Sandstorm" when the grain closes or I navigate away.

**Comment by ocdtrekkie** [comment] 2015-09-20 04:42
This is probably the same as #840? It sounds like you have maybe found a more general case of the same issue.

**Comment by ocdtrekkie** [comment] 2015-09-21 23:49
#840 and #903 should probably be generalized even further: If you have grains open, and navigate to "Open" or "New", the title remains whatever the last grain you were on. So really, the issue is that navigating to "Open" or "New" does not change the page title.

**Comment by zarvox** [comment] 2015-10-08 19:45
Fixed by #980.

**Closed by zarvox** 2015-10-08 19:45 UTC
