### ISSUE TITLE
What function to unpack spk file in sandstorm ui?

### ISSUE THREAD

**Issue by clickgumshoe** [sandstorm-io/sandstorm#3138] opened 2019-05-14 17:44 UTC
I will custom sandstorm code & need to find unpack spk function. My purpose is: copy some file that no ship with apk file by default. So i can add my code after unpack job complete, to copy my file in /opt/sandstorm/var/sandstorm/apps/<packageId>/

Thanks a lot.

**Comment by ocdtrekkie** [comment] 2020-01-15 16:29
Duplicate of #3139

**Closed by ocdtrekkie** 2020-01-15 16:29 UTC
