### ISSUE TITLE
`spk dev` fails if a file instead of a directory named tmp is mapped in

### ISSUE THREAD

**Issue by jparyani** [sandstorm-io/sandstorm#40] opened 2014-07-10 06:55 UTC
For example, if you have a file (not a directory) named tmp in the current working directory, and your sourceMap has "." as its first searchPath, then `spk dev` will fail when you try to create a grain. sandstorm.log outputs the following:

*** Uncaught exception ***
src/sandstorm/supervisor-main.c++:883: error from OS: 16m,nr_inodes=4k,mode=770"): Not a directory
stack: 0x7fae9b0300ad 0x7fae9b033aa7 0x417e5f 0x411dc4 0x411a72 0x411a59 0x411a4a 0x7fae9b03c9ce 0x7fae9b03e357 0x7fae9b030748 0x7fae9b036b43 0x40810a 0x7fae9a043b45 0x407b59
Exception while invoking method 'openSession' Error: Grain never came up.
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:326:15)
    at waitPromise (app/server/proxy.js:70:35)
    at startGrainInternal (app/server/proxy.js:343:10)
    at continueGrain (app/server/proxy.js:262:10)
    at Meteor.methods.openSession (app/server/proxy.js:135:19)
    at maybeAuditArgumentChecks (packages/livedata/livedata_server.js:1487)
    at packages/livedata/livedata_server.js:643
    at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
    at packages/livedata/livedata_server.js:642
    at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
    - - - - -
    at Socket.<anonymous> (app/server/proxy.js:338:14)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)
sandstorm-supervisor exited with code: 1

**Comment by paulproteus** [comment] 2015-05-02 01:22
@zarvox, in case you feel like familiarizing yourself more with the C++/sandboxing code, this might be fun.

**Comment by dwrensha** [comment] 2016-10-01 00:37
I am unable to reproduce this error. It appears to have been fixed by https://github.com/sandstorm-io/sandstorm/commit/8589f11af3dbfc723c5a929fc0b2a20b55759172, which goes with the "force the union FS to have directories in all these locations regardless of what's in the source directory" option.

**Closed by dwrensha** 2016-10-01 00:37 UTC
Labels: bite-size, usability
