### ISSUE TITLE
Cannot login via github

### ISSUE THREAD

**Issue by lsde** [sandstorm-io/sandstorm#200] opened 2015-01-08 03:36 UTC
Hi,
i'm unable to login via github account
Fully updated ubuntu 14.04, clean install, clean sandstorm-59
log shows:
==> sandstorm.log <==
{"line":"398","file":"oauth_server.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with GitHub. bad_verification_code","time":{"$date":1420688093447},"level":"warn"}
Exception while invoking method 'login' Error: Failed to complete OAuth handshake with GitHub. bad_verification_code
    at getAccessToken (packages/github/github_server.js:50)
    at Object.userAgent [as handleOauthRequest] (packages/github/github_server.js:5)
    at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8)
    at middleware (packages/oauth/oauth_server.js:173)
    at packages/oauth/oauth_server.js:146

**Comment by lsde** [comment] 2015-01-08 03:47
using firefox 36.0a2
same in chrome 39.0.2171.95

**Comment by kentonv** [comment] 2015-01-08 21:34
Hmm, probably something got copied into the wrong place when following the Github setup instructions. You may want to try clearing the config and trying againt:

1. Run at the shell: `sudo sandstorm mongo`
2. At the Mongo prompt, do: `db.meteor_accounts_loginServiceConfiguration.remove({})`
3. Redo the login configuration in the browser, making sure to precisely follow the instructions that appear in Sandstorm.

Note that the purpose of the instructions is to configure your server so that it can accept github logins, not to log you in personally. Sometimes people get confused here and try to somehow use their own personal username and password as client ID / secret -- that's not what these mean. Just do exactly what the instructions say. :)

Let me know if this helps.

**Comment by mstn** [comment] 2015-01-19 20:11
I have the same problem with same error in log. I followed your instructions. But the problem wasn't solved.

Details:
ubuntu 14.04
firefox 31.0
I am running ubuntu in a virtual box

**Comment by kentonv** [comment] 2015-01-19 20:29
@mstn Hmm, is it possible your `BASE_URL` in `/opt/sandstorm/sandstorm.conf` does not exactly match what you type in your browser? It needs to match exactly, including protocol (http vs. https) and port number.

**Comment by mstn** [comment] 2015-01-19 21:39
No. They match. In /opt/sandstorm/sandstorm.conf I have the default local address http://local.sandstorm.io:6080. Is it possible that github handshake process is not able to resolve the domain name?
(Btw thanks for working on this project. It looks very nice!)

**Comment by kentonv** [comment] 2015-01-19 21:58
Sandstorm connects to Github but Github does not connect to Sandstorm. So, Github doesn't need to resolve your server, but your server does need network access. The error message seems to indicate that this isn't the problem, though.

Hmm, I just installed Sandstorm from scratch, using install.sandstorm.io, using all-default settings (except that I chose non-root, but that shouldn't affect this), then did the github setup, and it seems to work. Did you do anything non-default? My sandstorm.conf ended up looking like this:

    SERVER_USER=kenton
    PORT=6080
    MONGO_PORT=6081
    BIND_IP=127.0.0.1
    BASE_URL=http://local.sandstorm.io:6080
    WILDCARD_HOST=*.local.sandstorm.io:6080
    MAIL_URL=
    UPDATE_CHANNEL=dev

**Comment by mstn** [comment] 2015-01-20 09:55
Good news. It works. 

Frankly, I do not remember how sandstorm.conf was yesterday, but today I found it messed up. For example, some variables were on the same line.

      WILDCARD_HOST=*.local.sandstorm.io:6080 MAIL_URL= UPDATE_CHANNEL=dev

I tidied up the file, restarted the server and now it works.

Thanks for your help.

**Comment by kentonv** [comment] 2015-01-20 22:46
How strange. Glad you got it figured out! Let me know if you ever figure out how it got that way.

@lsde could this be the problem for you too?

**Comment by kentonv** [comment] 2015-01-24 06:51
I'm going to merge this into #214 since what I describe there should solve most of this class of problem.

**Comment by kentonv** [comment] 2015-01-24 06:53
Oh right, Github only has a "duplicate" tag but doesn't let you choose what it's a duplicate of; you have to say in a comment. This is not really a "duplicate", so I'll just leave the tag off and say:

### closing in favor of #214

**Closed by kentonv** 2015-01-24 06:53 UTC
