### ISSUE TITLE
Account Settings - Multiple Identities

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#865] opened 2015-09-10 18:26 UTC
Currently:

![image](https://cloud.githubusercontent.com/assets/855341/9797150/7e7a4994-57ae-11e5-81d9-c59f6cf8d496.png)

Ideally something closer to this:

![shelldoc-myaccount6](https://cloud.githubusercontent.com/assets/855341/9797168/a61430e6-57ae-11e5-8170-84d2f7439725.png)

**Comment by kentonv** [comment] 2015-09-11 00:20
* I would prefer not to have the little pencils that need to be clicked to start editing. This would take extra work to implement and I feel that they would actually make the UX worse overall -- it's an extra thing to click on and I suspect some users won't get it.
* I think we need a "save" button on the editor form.
* The profile editor is too wide for most screens. We need a design for what happens when it gets thinner.
* We will soon need to decide how we're going to handle multiple identities here.

**Comment by neynah** [comment] 2015-09-11 00:25
Sure, I'll work on a revised mock-up.

**Comment by neynah** [comment] 2015-09-18 00:51
Two revised layout options designed at the minimum 900px width for desktop.

- maybe a disconnect icon is better than trash for removing an identity?
- is it worthwhile to mention what "Main identity" means for the user?
- am I missing anything?

![shelldoc-myaccount7](https://cloud.githubusercontent.com/assets/855341/9949430/5f31dfee-5d61-11e5-90d7-6480f871853e.png)
![shelldoc-myaccount8](https://cloud.githubusercontent.com/assets/855341/9949429/5f31c8d8-5d61-11e5-973c-5899529d3b22.png)

**Comment by zarvox** [comment] 2015-09-18 03:41
**Higher-level how-do-we-want-things-to-work questions:**

* Do we have a way to distinguish the global Account information from the list of Identities?  Or is the stuff in the white-backgrounded rectangle supposed to be editing some information about the currently-selected Identity?  I'm not sure what the nouns and groupings are here.
* When are Identities used as opposed to Accounts, so I can know what "set default identity" will actually do?
* Does each Identity have an email address, or does each Account?  If it's bound to Identities, they shouldn't be editable, since your email address (particularly for login-by-email identities!) is approximately equivalent to the identity.  If it's bound to Account, then we probably **don't** want to send service-related emails to all N identities that a user may have, but rather let them specify a primary email address from their set of confirmed email addresses, which means that should probably be radio buttons or just entries in a table.  Take a glance at https://github.com/settings/emails for an example of one way to do it.

Perhaps we could label the list of identities "Linked identities".  (We may also want to add a + Link another identity cardbutton at the end of the list, to make it clear that you can link more, and provide users with a way to enter that workflow?)

Stylistically, I like option 1 better if the information in the white-backgrounded rectangle is supposed to be a callout of one of the three identities on the left.  Option 2's "Usage" header looks weird right under the "My Account" header of equivalent size, with no in-between content, but I like that the main identity is labeled on the card, so you can see which one it is in all views.

**Usability/size whining:**

Hmmm, the text seems pretty tiny here, which makes it both harder to read and appears to be making the button click targets rather small and somewhat indistinct.  What pt or px size is this?  It's substantially tighter-packed than the text elsewhere in the shell, and probably should be closer in size.  I think we should try pretty hard not to use type smaller than `font-size: 12px` (which at 96dpi I think is 8pt?).  I'm handwaving here, but 14px for headings, 13px for most text, and reserve 12px for less-important explanatory text?

I feel like click targets in our UI in general should probably be no shorter than 26 pixels device-independent pixels at the absolute minimum, with a preference for at least 32px or so for primary action buttons, text fields, dropdowns, and so on.  By my measurements, the Save and Cancel buttons come out to 19 or so at present, which is small enough to make them difficult to hit for users with limited mobility.

Happy to discuss more in person tomorrow :)

**Comment by neynah** [comment] 2015-09-18 04:16
The identity that is being edited will 1. display the main identity by default, 2. or display whichever identity is selected. I'll get a better idea of how to make design changes depending on what the requirements are which we should discuss tomorrow. My understanding seems limited now.

Sure we can up the text to 12px- the smallest text I have is 11px so it won't be much of a change but perhaps enough of a change?

If the text & buttons will be large and we may be adding additional features to the multi identity section than what I have here then I think we will likely be moving usage below or perhaps on a separate page.

**Comment by neynah** [comment] 2015-09-23 18:41
- more obvious which identity is being edited
- added "primary e-mail" section at the top (I'm pretty sure I'm missing some things)
- shifted usage down
- added "log out of all identities"- is this a good spoit for it?
![shelldoc-myaccount9](https://cloud.githubusercontent.com/assets/855341/10054781/cb41e0e6-61e7-11e5-9f0f-eba181337f12.png)

**Comment by zarvox** [comment] 2015-09-23 22:43
"Log Out of All Identities" doesn't quite make sense to me.

The purpose behind the button was that you could force a logout of all *other* browser sessions, in the event one of your identities was compromised and the attacker might have a live Sandstorm login.  This way, once you've re-secured your compromised identity from your identity provider, you can re-secure your Sandstorm account by expiring all other logged-in sessions.

I'd rename it to "Log out all other sessions" or something like that.  Given infinite time and space, I'd want to offer something akin to the functionality https://github.com/settings/security offers under Sessions, or what you get in Gmail when you click the "Details" link way at the bottom of the page on the right under "Last Account Activity".

**Comment by zarvox** [comment] 2015-09-23 22:50
I don't see a way to add an email address or a new linked identity in this design.

Also, when possible, prefer radio buttons to dropdowns, since they don't require interaction to see the information they contain.  I know this trades off against available space, though I think in general it's a good use of said space.

Perhaps we have more total content here than should all get stuffed into a single account page.  Perhaps we want additional subpages for these features?  It'd make for better use of the space, particularly for self-hosters where they don't need space for Usage or Payment Methods.

**Comment by paulproteus** [comment] 2015-09-23 22:54
FWIW I actively prefer a drop-down chooser for primary email address but I
can live with either. I think changing this is going to be super rare. I
like that a drop-down doesn't confront me with information that I know is
wrong; when I give GitHub an email address of github@asheesh.org, I hope to
only really see that used on GitHub and don't particularly need to be
confronted with it here.

But again I can live with whatever.

**Comment by neynah** [comment] 2015-09-23 23:30
If there were only a small number of e-mail addresses then I would favour a bullet list (like the Pinterest one below). From what I understand, there is no limit on the number of e-mails a user can have.

In the current mock-up, the primary e-mail section is currently at the top of this page. As @paulproteus also mentioned, this makes it harder for me to see that a user would value seeing a bullet list of options (that they will likely not change) each time they visit this page.

If we end up going with a bullet list then I suggest that it should be moved to be below the linked identities/editing section.

As this page continues to expand in terms of features and space required, i agree that we should probably look into subpages.

![image](https://cloud.githubusercontent.com/assets/855341/10061552/b2c6f700-620e-11e5-99eb-243c04e7b88b.png)

**Comment by neynah** [comment] 2015-09-23 23:45
Or as you showed me earlier we could display something similar to this (I just don't think it should be displayed this way if it's at the top of the page).

![image](https://cloud.githubusercontent.com/assets/855341/10061941/65c26238-6212-11e5-8bb2-8679e6f9ea45.png)

**Comment by zarvox** [comment] 2015-09-24 00:21
I agree that the primary email address selector probably belongs below the general identity editing block.  You're less likely to change that than e.g. your avatar, or handle.

**Comment by neynah** [comment] 2015-09-24 00:27
In the future it would be cool to have the option to set an avatar for all their identities/quicker way than uploading the same image for each identity.

**Comment by zarvox** [comment] 2015-09-24 00:54
Could keep a set of avatars you've uploaded, and let you choose between them, a la Gravatar: https://en.gravatar.com/emails/

**Comment by neynah** [comment] 2015-09-25 19:03
This update assumes that usage & payment methods will be on a separate page/subpage...
![shelldoc-myaccount11](https://cloud.githubusercontent.com/assets/855341/10109418/a8bcfb24-637b-11e5-91c4-9aeff0f9ead4.png)

**Comment by ocdtrekkie** [comment] 2015-09-25 19:09
@neynah "Usage & Payment" should probably be a lot more apparent on that mockup as a place you can go, as opposed to a subheading. Grey is primarily used in this UI as descriptive text (see after "Primary e-mail" and below "Username", and the tiny Usage & Payment doesn't look clickable.

**Comment by neynah** [comment] 2015-09-25 19:35
Yes! I forgot to style it- thanks for pointing that out.

**Comment by kentonv** [comment] 2015-09-25 21:50
Looking nice.

I think we need a way to choose which identities are trusted for login.

The "add a new email address" box presumably adds a new email identity, and so is redundant with clicking email under "link new identity". It may make sense to have redundant UI here, though, since a lot of users won't intuitively understand that these are the same operation. Just making sure we're on the same page.

**Comment by zarvox** [comment] 2015-09-25 22:36
Re: untrusting identities for login: then we also need to make sure you don't disable all of your login identities, or unlink/dispose of your last login identity, lest you be unable to log in.  Can you think of any other dangerous corner cases that disabling login triggers?  (My gut feeling is that a very small fraction of users will discover this feature or find it useful, but I recognize that you are one of those users :) )

What should we show when you've successfully authenticated as an identity that has had its login disabled?  I think that's going to need a separate screen, and should perhaps suggest that the user try authenticating as that account's default identity instead.

Note that the Link new identity buttons as depicted will need to respond to the pool of currently-enabled identity providers.  Also, we don't know how many of those there will be in advance, and the email login will need a form, and if/when we support LDAP login, that'll also need a form...so maybe having a single button/link that simply takes you to a "login with your additional identity" page with that login form makes the most sense.

**Comment by ocdtrekkie** [comment] 2015-09-26 00:29
@zarvox Good catch at the end there. I definitely don't want to be locked into the current login providers supported by Sandstorm.

**Comment by neynah** [comment] 2015-10-05 02:16
- Added unlink icons to identities
- Adjusted "Link New Identity" section to just have a button rather than display each individual identity provider.

I think these changes also make a good case for keeping the "add new e-mail" section.

![shelldoc-myaccount12](https://cloud.githubusercontent.com/assets/855341/10271864/45809a18-6acc-11e5-8693-6aa5e0ffde19.png)

**Comment by neynah** [comment] 2015-10-15 21:08
- Still need to draft the warning text.
![unlink-edit](https://cloud.githubusercontent.com/assets/855341/10527602/3b3be4e0-7346-11e5-8e79-4739f5bd4845.png)

**Comment by paulproteus** [comment] 2015-10-15 21:13
FWIW for inspiration:

* https://plus.google.com/+FotosGeorgiadis/posts/JKprQiAKVxD

*
https://www.google.com/search?q=github+danger+zone&num=100&espv=2&source=lnms&tbm=isch&sa=X&ved=0CAgQ_AUoAmoVChMInb7rjbLFyAIVwYwNCh2uxAbU&biw=1247&bih=1006&dpr=2

**Comment by dwrensha** [comment] 2015-10-15 21:13
The user also needs to be able to change which identity is the main identity, and to be able to edit which identities allow login.

**Comment by neynah** [comment] 2015-10-15 21:19
@dwrensha Yes about changing their main identity. I intended on displaying this function on the editing pages of the other identities. (As in a button that says: "Make this my main identity") Is this alright or does anyone have a better suggestion?

Also, this means we should be able to activate/disable login on a per-identity basis?

**Comment by neynah** [comment] 2015-10-15 21:20
@paulproteus I like the danger zone but if it's not tooooooo dangerous then perhaps we also don't want to draw much attention to it. What's the worst that could happen if someone unlinks their identity? I guess I'd like an accurate idea of magnitude.

**Comment by dwrensha** [comment] 2015-10-15 21:24
> Yes about changing their main identity. I intended on displaying this function on the editing pages of the other identities. (As in a button that says: "Make this my main identity") Is this alright or does anyone have a better suggestion?

Works for me

> Also, this means we should be able to activate/disable login on a per-identity basis?

Yes, each identity can either allow login or not.

**Comment by neynah** [comment] 2015-10-15 22:31
Presumably you can't unlink your main identity unless you first change your main identity? Or, we let them unlink and they either have to choose a new main identity or we automatically set one...

**Comment by neynah** [comment] 2015-10-16 00:15
![myaccount-draft10](https://cloud.githubusercontent.com/assets/855341/10530843/23283aa6-7360-11e5-9c13-137c7d78de97.png)

**Comment by zarvox** [comment] 2015-10-16 01:13
A couple comments:

* It's currently not easy (possible?) to tell which identity is associated with a grain, which makes the Danger Zone warning not particularly actionable.  I guess this is less of a problem because until identity merging lands, people can't merge identities.  But perhaps we should indicate which identity owns which grain, if it's important here?

* Consider making the Danger Zone stripe a shade between the background grey and the active-field white - it currently looks like such a strong separator that the content below it feels disconnected from the content above, despite their relation.  Alternately, give the stripe some margin on the sides, so that the white bleeds through on either side?

* Maybe prefer radio buttons to toggle the Enabled/Disabled state of login, or a checkbox?  I can't tell which state is currently active at a glance.  Consider making the options verbs that say what they do, rather than making the user do the computation: "Allow login" "Disable login"

* For a one-button form, the Save/Cancel buttons for "Login for this identity seem confusing.  Drop them in favor of making the toggle self-sufficient.

**Comment by neynah** [comment] 2015-10-16 02:52
@zarvox Yeah I'll explore different options for danger zone. A lighter grey would be good (I would think).

I'm not thrilled about radio buttons unless there is a save button nearby or some sort of animation or text indicating it's been updated. E.g. with radials we could have text updating to say "Login for this identity is enabled" / "Login for this identity is disabled." Thoughts?

+1 on the verbs.

**Comment by kentonv** [comment] 2015-10-16 23:39
I think radio buttons are pretty ugly. A lot of modern UIs use a "toggle switch" graphic. Some examples:

https://www.google.com/search?q=toggle+switch+ui&tbm=isch

**Comment by ocdtrekkie** [comment] 2015-10-17 00:07
@kentonv A toggle switch is a very different UI pattern that a radio button. A radio button indicates a "pick one" structure, where a toggle switch is much more like a checkbox or "pick many" structure.

One could potentially suggest users may want to notify multiple email addresses here, hence toggle switches, but if you wanted to retain a "pick one" functionality, without radio buttons, you'd be looking for a dropdown box, I believe.

**Comment by kentonv** [comment] 2015-10-17 00:38
@ocdtrekkie - I was specifically replying to the radio button suggestion being discussed in the two comments before mine, for choosing whether to enable login for a particular identity. That is in fact a boolean case.

For choosing an email, I'm fine with what nena has designed.

**Comment by zarvox** [comment] 2015-10-17 00:50
@neynah All right, how about radio buttons + a save button which is disabled if the current state of the radio button is unmodified from it's server-side state or after the user submits the form?

Another thought: if we'll have multiple Save buttons on a page, it might be nice to have a thin rectangle around each form, to indicate what edits you may have made will be committed when you click this "Save" button.

@kentonv I think usability should trump subjective ugliness.  Radio buttons are almost universally more usable than the alternatives - they don't require the user to do mental gymnastics to figure out which button state is active or what that means when applied to the options.  My experience with toggle switches is that I universally have to reread the option and spend some time figuring out what "left" or "right" mean (which may be further confused by the fact that the label may be on the opposite side of the thing indicating state).  Aligned text is just much faster to deal with.

Another issue with toggle switches with on/off or enabled/disabled labels is that they are ambiguous as to whether they are displaying the current state of the system or if they are showing the action that will be taken when the control is triggered.  (Preventing this ambiguity is what underlies my frequent requests for all buttons representing actions in the UI to be labeled with verbs describing what will happen when triggered.)

Showing two buttons and highlighting one with color when there's only two options makes it hard to tell whether the left or the right button is currently "pressed".  Additionally, if there's a pattern of using noticeable buttons to highlight the actions that can be taken on a page, then switching back to showing states here is somewhat confusing, particularly if we don't want to be highlighting this more-dangerous part of the page.

If we can come up with a design that's as usable as radio buttons, then I'm open to other options, but radio buttons are tried and true, work well everywhere, are familiar, and allow for clear phrasing and explanation of each item.  (And they work well at arbitrary screen widths.)

**Comment by kentonv** [comment] 2015-10-17 01:08
@zarvox When I am already familiar with an option, a radio button forces me to read the labels to determine which state is which. In cases where the option has obvious "on" and "off" states -- as I think is the case here -- I find a toggle or check box easier to process. While I agree that the toggle in Nena's mockup is somewhat ambiguous, there are plenty of toggle switch designs out there which are not ambiguous in the ways you describe.

**Comment by dwrensha** [comment] 2015-10-21 22:13
Travis has some nice flick switches:
<img width="369" alt="travis" src="https://cloud.githubusercontent.com/assets/495768/10651767/6621eeb0-781f-11e5-87ec-6e3af0258fb4.png">

**Comment by neynah** [comment] 2015-10-21 22:19
+1 @dwrensha I think these are great. I'll give the toggling and radio buttons another shot and go from there.

**Comment by dwrensha** [comment] 2015-10-21 23:02
I think we're also going to need an icon for identities that have no associated authentication scheme. Demo users fall into this category, and we're planning to make it easy to create new authentication-less identities from within the accounts UI.

**Comment by dwrensha** [comment] 2015-10-21 23:06
It occurs to me, however, that maybe having no icon at all for such users would be entirely appropriate.

**Comment by dwrensha** [comment] 2015-11-17 20:21
The latest design has a button for "Usage & Payment". I think it would make sense for this area of the page to act like tabs. So there would be a "Profile" button in addtion to the "Usage & Payment" button, similar to bit in a previous design:
![account-settings-tabs](https://cloud.githubusercontent.com/assets/495768/11221952/d17238f2-8d35-11e5-95f1-787b92abcb03.png)

We also need a better design for the login interstitial, which currently looks like:
<img width="1012" alt="login interstitial" src="https://cloud.githubusercontent.com/assets/495768/11222226/583826e8-8d37-11e5-8aad-fef35b69cc23.png">

We should also clean up the design for the identity switcher, which currently looks like:
<img width="1276" alt="identity switcher" src="https://cloud.githubusercontent.com/assets/495768/11222943/4105df5c-8d3b-11e5-8712-ac3c5cd7fa78.png">

According to @kentonv, this identity switcher should be part of the top-right account dropdown, rather than its own topbar item (see https://github.com/sandstorm-io/sandstorm/pull/1161#issuecomment-157228882).

**Comment by neynah** [comment] 2015-11-18 18:59
For the login interstitial is it possible to for them to login by clicking these identity cards rather than having to click back? e.g.

![notaloginidentity-draft1](https://cloud.githubusercontent.com/assets/855341/11250807/2ddeaac8-8de3-11e5-85bc-54b6db5bdbe1.png)
I also coloured the message red as I figured it was like an error message- bringing attention that they need to take an action. Let me know if that makes sense or not. :)

I guess it seems odd that "cancel" and unlinking accounts are the only actions that the user can take.

(Other mock-ups in progress)

**Comment by dwrensha** [comment] 2015-11-18 23:39
I like the red message.

Implementation-wise it would tricky to make clicking on a card mean "log in as this identity". A possible alternative might be to put the usual login buttons list on this page.

**Comment by kentonv** [comment] 2015-11-19 18:52
I think that clicking on a card should simply initiate login with the login provider used by the identity displayed in the card. E.g. if the card shows a Github identity then initiate github login. It's possible that the user is logged in as some other Github user and thus they'll end up logged in as the wrong account, but I think 95% of the time it'll work out correctly. E.g. if I'm trying to log in as twitter:SandstormIO and I'm presented with this prompt asking me to choose if I'm Kenton or Jade, I'm obviously going to choose Kenton, and that should work correctly.

Later on, we can add some sort of detection for the case where this ends up using the wrong identity, and then show the user some instructions on what to do about it ("Oops, you meant to log in as twitter:KentonVarda but it looks like you're still logged in as twitter:SandstormIO. You will need to visit Twitter and log out. Please go do that now and then click "try again". [try again] [cancel]").

On another note, I'm worried that people may mindlessly click on the "unlink" button in an attempt to continue without reading the label. We'll need an "are you sure?" prompt. But, maybe it makes sense instead to have a single button that is above or below the whole list that initiates "unlink" mode, kind of like the "uninstall" button on the app list. Possibly the button should have some explanatory text around it saying what this means.

**Comment by paulproteus** [comment] 2016-02-12 21:30
@neynah says this is closed, so I am going to mark it as such!

**Closed by paulproteus** 2016-02-12 21:30 UTC
