### ISSUE TITLE
About page leaves file picker UI instead of being a tab

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#244] opened 2015-02-06 16:23 UTC
It'd be nice if you didn't need the back button to get back from the About page when we have a sidebar UI. :)

**Comment by paulproteus** [comment] 2015-02-06 17:09
Just writing this up to help others understand the bug better. Steps to reproduce:

* Visit https://demo.sandstorm.io/
* Click "Start the demo"
* Notice you are in Sandstorm, which looks great
* Click "About" on the left nav
* Decide you've learned enough about Sandstorm, and want to go back.

Actual behavior: You have to use the back button in your browser since the sidebar's "All files" link has vanished.

Expected behavior: You could click on 'All files' and go back.

**Comment by zarvox** [comment] 2015-10-30 22:50
Closing this one, since I think it's obsoleted by the shell redesign. :)

**Closed by zarvox** 2015-10-30 22:50 UTC
