### ISSUE TITLE
etherpad errors in debug .. no recursion ?  "client - too much recursion'

### ISSUE THREAD

**Issue by melissabutterfly321** [sandstorm-io/sandstorm#2368] opened 2016-08-11 16:15 UTC
...: _.object is not a function -- { errorId: '7ajoqzosQTInVWoi2ZC4',
  msg: 'TypeError: _.object is not a function',
  url: 'https://9451b9cf196b5b498d81e4d3f1e68c43
  linenumber: 131,
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.2357.130 Safari/537.36' }
[2016-08-11 09:10:24.872] [INFO] ueberDB - Flushed 1 values
[2016-08-11 09:10:27.584] [INFO] ueberDB - Flushed 3 values
[2016-08-11 09:10:27.743] [WARN] client - too much recursion -- { errorId: 'OGQR7XuEvX0NPo5hk6T9',
  msg: 'too much recursion',
  url: 'https://9451b9cf196b5b498d81e4d3f1e68c43
  linenumber: 72,
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.2357.130 Safari/537.36' }

**Comment by kentonv** [comment] 2016-08-12 23:15
Duplicate of #2367

**Closed by kentonv** 2016-08-12 23:15 UTC
