### ISSUE TITLE
auto sign-out

### ISSUE THREAD

**Issue by jadeqwang** [sandstorm-io/sandstorm#770] opened 2015-08-28 03:46 UTC
https://youtu.be/OH7iaiYLeeU

![image](https://cloud.githubusercontent.com/assets/1584904/9538765/a89837a2-4cfc-11e5-87a3-469f83160f91.png)

If I sign out while a grain is open, then sign back in immediately, I get immediately signed out.

**Comment by neynah** [comment] 2016-03-25 21:43
Tried this today:

1. Attempted to access a Wekan grain while not-signed in
2. Signed in and Wekan grain opened
3. Signed out and arrived on Oasis landing page
4. Signed in and arrived on grains page
![screenshot- 269](https://cloud.githubusercontent.com/assets/855341/14054401/2910f024-f296-11e5-84c2-8e586ff99435.jpg)
![screenshot- 270](https://cloud.githubusercontent.com/assets/855341/14054409/3cdea8a8-f296-11e5-8960-362e8cdc6e0d.jpg)
![screenshot- 271](https://cloud.githubusercontent.com/assets/855341/14054419/5269b064-f296-11e5-8255-4a2e7e13de6b.jpg)
![image](https://cloud.githubusercontent.com/assets/855341/14054617/c7f8db9c-f297-11e5-996b-71cec393ee28.png)

It seems like the exact same flow in the video (in August) doesn't exist anymore since signing in takes you to your grains page.

**Comment by kentonv** [comment] 2016-03-26 00:19
At one point it was the case that if you rapidly signed out and back in, then, no matter what page you were on, you'd shortly get signed out again. However, I can't reproduce this currently. I guess I'll close this.

**Closed by kentonv** 2016-03-26 00:19 UTC
Labels: usability
