### ISSUE TITLE
"Who has access" expands from an invisible button

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#2206] opened 2016-07-12 16:06 UTC
When I click "See who has access" from a Share button in Edge, it appears to expand from an invisible button.

![whohasaccess](https://cloud.githubusercontent.com/assets/4399499/16774168/84b6e5de-4820-11e6-924e-fb24d2d94038.png)

Oddly, I submitted this issue as #2205 and GitHub ate it. It doesn't appear in the issues tab or my activity. I'm mystified.

**Comment by dwrensha** [comment] 2016-07-12 16:42
Closing as duplicate of #2205.

**Closed by dwrensha** 2016-07-12 16:42 UTC

**Comment by dwrensha** [comment] 2016-07-12 16:47
I've also noticed that occasionally GitHub takes longer than you would expect to percolate an event. In any case, #2205 looks totally fine now.

**Comment by ocdtrekkie** [comment] 2016-07-12 16:55
Yeah, after filing the dupe and realizing "this is a GitHub problem", I checked Status and they had something going on.
