### ISSUE TITLE
Editing a calendar event in SandCal gives error

### ISSUE THREAD

**Issue by higherarch** [sandstorm-io/sandstorm#3444] opened 2020-10-03 13:53 UTC
I apologize if this is the wrong place for this. 
I installed sandstorm on a Linode last night. installed the SandCal app and input a date in the grain. 
This morning when I went to edit... No dice I have attached a picture of the error.
This is my first time contributing to anything bug or otherwise. I believe in what you are doing and will help as much as I can. Keep up the great work!
![Screenshot_20201003-064303](https://user-images.githubusercontent.com/30538851/94993334-21a0ca00-0545-11eb-8e9e-24dc4a8c57d5.png)

**Comment by ocdtrekkie** [comment] 2020-10-03 13:57
Generally speaking, bugs with apps should be reported to the app directly (in this case, https://github.com/zenhack/sandcal) though @zenhack will also see it here.

My guess is you found a hole in the input validation. Do you by chance know what you entered, or can screenshot how you entered it (perhaps, using another SandCal grain)?

**Comment by zenhack** [comment] 2020-10-03 19:12
I suspect @ocdtrekkie is right re: the root cause; if you can reproduce this, please let us know exactly what inputs you supplied, and a screenshot would be useful as well there.

Also, what os/browser/version are you using?

Right now SandCal just sets the input type and relies on the browser todo client-side validation, so perhaps you're using a browser whose time input doesn't line up with our expectations.

**Comment by higherarch** [comment] 2020-10-19 14:35
thanks for fixing it so quickly! it works fine now after update. I haven't
had problems with it... Is there anything I can do to support you guys
other than just getting the word out?

**Comment by higherarch** [comment] 2020-10-19 14:36
Firefox 81.0.2 (64)

**Comment by ocdtrekkie** [comment] 2020-10-19 14:51
@higherarch The SandCal update was I think for an unrelated bug, so you might still see this issue! (You can see the changelog here: https://github.com/zenhack/sandcal/blob/master/CHANGELOG.md) If you have any further issues, try to get us exactly what you entered in that caused it to fail, so Ian can reproduce it. Since you're not having the issue now, I'll go ahead and close this issue for the time being.

Getting the word out is definitely a very beneficial way to support us. Reporting issues and suggesting features is also valuable, we're always happy to have new perspectives on where we should be focusing and what pain points people are experiencing.

If you are looking to financially support the Sandstorm community, @zenhack (the author of SandCal, and one of the most active Sandstorm developers right now) has a GitHub sponsors page at https://github.com/sponsors/zenhack which directly helps keep Sandstorm development moving. We also started an OpenCollective at https://opencollective.com/sandstormcommunity though we haven't really drawn any money from it yet.

**Closed** 2020-10-19 14:51 UTC
Labels: app-issues
