### ISSUE TITLE
after uploading spk, "Most Used" apps get a truncated second row

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#1095] opened 2015-10-29 19:19 UTC
looks like this:
<img width="1201" alt="cutoff" src="https://cloud.githubusercontent.com/assets/495768/10829451/6f0fb570-7e50-11e5-970c-f126903cf5e0.png">

**Comment by zarvox** [comment] 2015-10-29 19:29
Hmmm, yeah, this is probably because we scroll to the highlighted app.  We should probably only do that for the apps' appearance in the "All apps" list, by making a narrower selector.

**Comment by zarvox** [comment] 2015-10-29 19:32
Actually, we can just remove highlighting from the "Most Used" list altogether, which also solves this.  Patch inbound.

**Comment by jadeqwang** [comment] 2015-11-04 20:13
Both @neynah and I have experienced this (which, in theory, should have been fixed by the above):

![image](https://cloud.githubusercontent.com/assets/1584904/10950604/4fd7d1d2-82ed-11e5-9d45-64a305a5d372.png)

@jparyani was saying that it's because the "most used" is scrolling to highlight the just-installed app where it is in the list of frequency of usage.

**Comment by zarvox** [comment] 2015-11-04 21:40
FWIW, the patch that fixes this is merged to master, but the patch is not deployed in an Oasis/Sandstorm release yet, which is why you're still hitting it.

Perhaps we should leave Github issues open until they are released?  Heavier-weight issue trackers like Bugzilla typically have multiple states to track things like "confirmed bug", "fix started", "fix committed", "fix released", "closed".

**Comment by paulproteus** [comment] 2015-11-04 22:12
Debian handles this by having *publishing* the fixed package be the event
that triggers GitHub issue closure.

Proposal 1:

I think I'd be +1 on the following:

* The Sandstorm release script looks at the GitHub issues supposedly fixed
in the commits going out, and then causes them to be actually closed them.
(However, getting that right is going to be a little complicated I fear.)


Proposal 2:

I think what I'd like to see is that, whenever a bug is marked resolved, it
gets the

pending-verification

label attached, and then we have "Bug fix verification parties" when we do
a release.

These constitute:

* On release day, everyone works together to look at bugs that are labeled
"pending-verification".

* We divvy those up, and each person does the following:

* For each bug they are responsible for, test if the bug seems fixed. If
so, remove the pending-verification label. Else, re-open.

Problems with Proposal 2:

* It requires automatically annotating bugs somehow still (@jparyani might
know how to do this easily? else e.g.
https://lostechies.com/joshuaflanagan/2010/10/26/extending-github-issues/
exists)


Proposal 3:

* Document in a contributor's guide that "bugs are fixed when fixes are
pushed to master, but aren't yet released" and

* Show a screenshot tour of how to get from a bug page to the commit that
fixed it, and

* Show a screenshot tour of how to get from a commit page to a tag aka
release in which the bug is fixed, and

* Show a screenshot tour of how to identify that a commit that is in master
is not yet in any release


I also think Proposal 3 is pretty reasonable. Curious what others think.

This is something that lots of organizations struggle with; I think the
most important thing is not so much what we decide but that we document it
somewhere and stick to it.

**Comment by zarvox** [comment] 2015-11-04 22:29
Proposal 3 seems fairly reasonable and relatively lower ongoing maintenance effort.

Also worth noting is that I think part of the reason that we're hitting things like this is that we've been working on some gnarly, higher-risk changes (multiple identities!  reworked storage!), which we're trying to keep from impacting users until they've been tested a bit more.  As a result, we're not pushing other low-impact bugfixes like this one, because it's also work to cut releases from not-master and it takes time and energy to deploy them.

Proposal 4: more frequent releases.

Proposal 5: do nothing, since doing anything might cost more time/effort than the confusion saved.

**Comment by kentonv** [comment] 2015-11-07 02:33
Github likes to auto-close issues when a commit claiming to fix the issue reaches master. I think trying to implement any policy that _doesn't_ involve closing on merge is going to be painful because of this.

What I have sometimes done in the past, though, is assigned the bug a "milestone" indicating the next release number. It is still kind of tedious, though.

The fix for this one is now live on Oasis, so I'm closing again.

**Closed by kentonv** 2015-11-07 02:33 UTC
